#!/bin/bash
# copy data to a named volume for grafana container to access.

SETUP=${1:-'default'}

docker volume create grafana

shell/docker/cp setups/$SETUP/volumes/grafana/grafana.cfg grafana /data/grafana
shell/docker/cp setups/$SETUP/volumes/grafana/devices.xml grafana /data/grafana
shell/docker/cp setups/$SETUP/volumes/grafana/styles grafana /data/grafana
