#!/usr/bin/env python3
# run a docker-compose yaml file with optional list of services

# usage: shell/setups/docker COMMAND SETUP [SERVICES]
# COMMAND can be start, startd, stop
# SETUP is the setup subfolder, eg vmc, ccs-pa
# SERVICES is an optional space-delim list of services to start/stop
# eg `shell/setups/docker startd ccs-pa agent`

import sys
import os
import pathlib

cmd = sys.argv[1]  # eg 'start', 'startd', 'stop'
setup = sys.argv[2]  # eg 'vmc'
services = ' '.join(sys.argv[3:])  # eg 'agent timescaledb'

# # get list of docker compose file paths
# files = [f"setups/{setup}/docker/{part}.yaml" for part in parts]
# args = ' '.join([f"--file {file}" for file in files])
composefile = f"setups/{setup}/compose.yaml"
args = f"--file {composefile}"

# add envfile
envfile = f"setups/{setup}/.env"
if pathlib.Path(envfile).exists():
    args += f" --env-file {envfile}"

# get flags
flags = ''
if cmd == 'startd':
    flags = '--detach'

if cmd == 'start' or cmd == 'startd':
    # pull any required images in the docker-compose files
    # and start the services
    cmd = f"docker-compose {args} pull && docker-compose {args} up --build {flags} {services}"
    print(cmd)
    os.system(cmd)

elif cmd == 'stop':
    cmd = f"docker-compose {args} down {services}"
    print(cmd)
    os.system(cmd)
