#!/bin/bash
# replay an mqtt recording

# SETUP=${1:-'default'}

# # replay mqtt recording - https://github.com/rpdswtk/mqtt_recorder
# replay MODEL='ccs-pa' RUN='run0' PORT='1883':
#     mqtt-recorder \
#       --host localhost \
#       --port {{PORT}} \
#       --mode replay \
#       --loop true \
#       --file models/{{MODEL}}/simulations/{{RUN}}.csv

