#!/usr/bin/env python3
# run a set of docker-compose yaml files
# eg `shell/setups/start ccs-pa db app`
# see also stop

import sys
import os

setup = sys.argv[1]
parts = sys.argv[2:]

files = [f"setups/{setup}/docker/{part}.yaml" for part in parts]
args = ' '.join([f"--file {file}" for file in files])

# . compile devices.yaml to devices.xml
# shell/setups/compile $SETUP

cmd = f"docker-compose {args} pull"
print(cmd)
os.system(cmd)

cmd = f"docker-compose {args} up --build"
print(cmd)
os.system(cmd)
