#!/bin/bash
# install applications

# upgrade all packages
sudo apt update
sudo apt full-upgrade

# upgrade node to v15
sudo apt remove -y nodejs
curl -sL https://deb.nodesource.com/setup_15.x | sudo -E bash -
sudo apt install -y nodejs
sudo npm install -g npm@latest

# note: raspberry pi os already has python/pip
pip3 install mqtt-recorder
npm install -g http-server

# install just - a command runner like make
# see https://github.com/casey/just
#. this grabs 64-bit version - no 32-bit avail in his releases yet. 
# see https://github.com/casey/just/issues/739
# uses go cargo to build?
# curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | \
#   sudo bash -s -- --to /usr/local/bin
