#!/bin/bash

# install docker-compose on friendlycore
# https://wiki.friendlyarm.com/wiki/index.php/FriendlyCore_(based_on_ubuntu-core_with_Qt)#How_to_install_and_use_docker_.28for_arm64_system.29

sudo apt-get update
sudo apt-get install docker.io

sudo apt-get install python-pip3

pip3 install docker-compose
# get
# WARNING: The script docker-compose is installed in '/home/pi/.local/bin' which is not on PATH.
# Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

echo 'PATH=$PATH:/home/pi/.local/bin' >> ~/.bashrc
source ~/.bashrc
#ok?

echo 'Done!'
