#!/bin/bash
# install docker
# see https://docs.docker.com/engine/install/debian/
# and https://docs.docker.com/compose/install/

# install and upgrade docker
curl -sSL https://get.docker.com | sudo sh
sudo apt upgrade -y docker

# allow user to run docker - else need `sudo docker ...`
sudo usermod -aG docker $USER
newgrp docker # activate group

# start docker service
# Docker Engine starts automatically on DEB-based distributions. 
#. On RPM-based distributions, you need to start it manually using 
# the appropriate systemctl or service command.
# On Debian and Ubuntu, the Docker service is configured to start on 
# boot by default. To automatically start Docker and Containerd on boot 
# for other distros, use the commands below:
# sudo systemctl enable docker.service
# sudo systemctl enable containerd.service

# install docker-compose
# docker compose is not yet included in the docker command for linux
#. For alpine, the following dependency packages are needed: 
# py-pip, python3-dev, libffi-dev, openssl-dev, gcc, libc-dev, rust, cargo and make.
# this only works for linux-x86
# $(uname -s)-$(uname -m) gives Linux-armv7l on my raspberrypi 4
# sudo curl -L "https://github.com/docker/compose/releases/download/1.29.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
# sudo chmod +x /usr/local/bin/docker-compose
sudo pip3 install docker-compose
