#!/bin/bash
# install docker
# see https://docs.docker.com/engine/install/debian/#install-using-the-convenience-script

# install and upgrade docker
curl -sSL https://get.docker.com | sudo sh
sudo apt upgrade docker

# allow user to run docker - else need `sudo docker ...`
sudo groupadd docker
sudo usermod -aG docker $USER
newgrp docker # activate group

# echo Now restart terminal - otherwise must use sudo with docker commands. 

# Docker Engine starts automatically on DEB-based distributions. 
#. On RPM-based distributions, you need to start it manually using 
# the appropriate systemctl or service command.
# On Debian and Ubuntu, the Docker service is configured to start on 
# boot by default. To automatically start Docker and Containerd on boot 
# for other distros, use the commands below:
# sudo systemctl enable docker.service
# sudo systemctl enable containerd.service

# install docker-compose - not yet in docker command?
# sudo apt -y install libffi-dev libssl-dev python3-dev python3 python3-pip
# sudo pip3 install docker-compose
