#!/bin/bash
# install applications

# upgrade all packages
sudo apt update
sudo apt full-upgrade

# upgrade node to v15
sudo apt remove -y nodejs
curl -sL https://deb.nodesource.com/setup_15.x | sudo -E bash -
sudo apt install -y nodejs
sudo npm install -g npm@latest

# note: raspberry pi os already has python/pip
pip3 install mqtt-recorder
npm install -g http-server
