#!/bin/bash
# install linux applications

# upgrade all packages
sudo apt update
sudo apt -y full-upgrade

# install direnv
# lets you change envars etc per directory/project
sudo apt install direnv
echo 'eval "$(direnv hook bash)"' >> ~/.bashrc
source ~/.bashrc
