#!/bin/bash
# install node and dependencies

# upgrade node to v15
sudo apt remove -y nodejs
curl -sL https://deb.nodesource.com/setup_15.x | sudo -E bash -
sudo apt install -y nodejs
sudo npm install -g npm@latest

(cd services/adapter && npm install)
(cd services/application && npm install)
(cd services/compiler && npm install)
(cd services/simulator-mqtt && npm install)
(cd services/simulator-opc && npm install)
(cd services/diode/code/application/datadiode/contrib/nodejs && npm install)
