#!/bin/bash
# install python dependencies

# create and use a virtual environment
python3 -m venv ~/.venv/ladder99-venv
source ~/.venv/ladder99-venv/bin/activate

# install requirements
pip3 install -r requirements.txt
