#!/bin/bash
# install python and dependencies

# use virtual environment

# sudo apt update
# sudo apt install python3-pip
# sudo apt install --upgrade python3-dev python3-venv

python3 -m venv .venv
source .venv/bin/activate

# install requirements
pip3 install mqtt-recorder
