#!/bin/bash

usage="
Usage: ./l99 disk SETUP

Print disk usage for a given setup.

SETUP is a client name or setup folder.

Example
    ./l99 disk demo
"

# show help if count of params is zero
if [ $# -eq 0 ]; then
    echo "$usage"
    exit 1
fi

# get setup folder

# # if starts with '.' treat as a setup folder, else a client name
# if [[ $1 = .* ]]; then
#     SETUP=$1
# else
#     SETUP=../setup-$1
# fi
# shift

# handle example setup specially
if [ $1 = example ]; then
    SETUP=setups/example
else
    SETUP=../setup-$1
fi
shift

# SETUP=../setup-$1
# shift

# show all disk usage
echo
echo Disk usage
df -h /

# show usage for the setup volumes
echo
echo Setup usage
CMD="du -d1 -h $SETUP/volumes/"
# sudo isn't always available, eg in git bash environment
if hash sudo 2>/dev/null; then
    sudo $CMD
else
    $CMD
fi
