#!/bin/bash

# Print disk usage for current setup.

# get setup folder
SETUP=$(cat .l99_setup)
SETUP_FOLDER=setups/$SETUP

# show all disk usage
echo
echo Disk usage
df -h /

# show usage for the setup volumes
echo
echo Setup usage
CMD="du -d1 -h $SETUP_FOLDER/volumes/"
# note: sudo isn't always available, eg in git bash environment
if hash sudo 2>/dev/null; then
    sudo $CMD
else
    $CMD
fi
