#!/usr/bin/env python3

import sys
import os
import pathlib

if len(sys.argv) < 2:
    print("""
Usage: shell/docker SETUP COMMAND [SERVICES]

Run a docker-compose yaml file with optional list of services.

SETUP     setup subfolder, eg vmc, ccs-pa
COMMAND   start, startd (run detached), stop (stop all services)
SERVICES  optional space-delim list of services to start

eg `shell/docker startd ccs-pa application`

Use `docker kill SERVICE` to stop a service
""")
    sys.exit(0)

setup = sys.argv[1]  # eg 'vmc'
cmd = sys.argv[2]  # eg 'start', 'startd', 'stop'
services = ' '.join(sys.argv[3:])  # eg 'agent timescaledb'

# # get list of docker compose file paths
# files = [f"setups/{setup}/docker/{part}.yaml" for part in parts]
# args = ' '.join([f"--file {file}" for file in files])
# composefile = f"setups/{setup}/compose.yaml"

# add main compose file for main agent-viz pipeline
composefile = f"setups/compose.yaml"
args = f"--file {composefile}"

# add compose file for device-agent pipeline / overrides
composefile2 = f"setups/{setup}/compose-{setup}.yaml"
if pathlib.Path(composefile2).exists():
    args += f" --file {composefile2}"

# add envfile
# envfile = f"setups/{setup}/.env"
envfile = f"setups/.env"
if pathlib.Path(envfile).exists():
    args += f" --env-file {envfile}"

# get flags
flags = ''
if cmd == 'startd':
    flags = '--detach'

if cmd == 'start' or cmd == 'startd':
    # pull any required images in the docker-compose files and start services.
    cmd = f"SETUP={setup} docker-compose {args} pull {services} && SETUP={setup} docker-compose {args} up --build {flags} {services}"
    print(cmd)
    os.system(cmd)

elif cmd == 'stop':
    cmd = f"SETUP={setup} docker-compose {args} down {services}"
    print(cmd)
    os.system(cmd)
