#!/bin/bash

usage="
Usage: l99 init SETUP

Initialize a new setup in ../setup-SETUP.

Example
    l99 init my-company
"

# show help if count of params is zero
if [ $# -eq 0 ]; then
    echo "$usage"
    exit 1
fi

# get setup name
SETUP_NAME=$1
shift

SETUP=../setup-$SETUP_NAME

# check if setup dir already exists
if [ -d "$SETUP" ]; then
  echo Error: a folder for $SETUP_NAME already exists at $SETUP. 
  echo Please try a different setup name.
  exit 1
fi

# save setup folder to file
echo $SETUP > .l99_setup

ENVFILE=$SETUP/.env

# copy setup
echo
echo Copying from setups/example...

# need `2>/dev/null || :` to suppress the error msgs and errors in cp,
# see https://serverfault.com/a/153893/211025.
# but
# rsync has an --exclude param, but installing rsync on git bash for windows is complex - 
#  https://superuser.com/questions/701141/how-to-add-more-commands-to-git-bash
# sudo cp -R setups/example $SETUP \
# cp -R setups/example $SETUP 2>/dev/null || : \
# && rm $ENVFILE \
# && rm -rf $SETUP/volumes/grafana/var \
# && rm -rf $SETUP/volumes/pgadmin \
# && rm -rf $SETUP/volumes/postgres \
# && rm -rf $SETUP/volumes/portainer \

# need to specify everything explicitly here - 
# alternative is installing rsync on gitbash, or ignoring cp errors, 
# or using sudo to cp everything including potentially large pg folders.
# so, will need to keep this up-to-date if add more to the example folder!

# this gives a warning message
# && cp setups/example/* $SETUP \
# && rm $ENVFILE \

# EXAMPLE=setups/example
EXAMPLE=$L99_HOME/setups/example

mkdir $SETUP \
&& mkdir $SETUP/volumes \
&& mkdir $SETUP/volumes/grafana \
&& cp -R $EXAMPLE/volumes/agent $SETUP/volumes/agent/ \
&& cp -R $EXAMPLE/volumes/grafana/etc $SETUP/volumes/grafana/etc/ \
&& cp $EXAMPLE/.gitignore $SETUP \
&& cp $EXAMPLE/.env-example $SETUP \
&& cp $EXAMPLE/compose-overrides.yaml $SETUP \
&& cp $EXAMPLE/README.md $SETUP \
&& cp $EXAMPLE/setup.yaml $SETUP \
&& echo Done. Try \'l99 start\' \
&& echo

