#!/bin/bash

# run a ladder99 shell command

# note: need #!/bin/bash in first line, NOT #!/bin/sh - led to bug on encabulator
# where it wasn't parsing [[ $setup = .* ]] correctly.
# some discussion here
# https://unix.stackexchange.com/questions/379464/why-does-this-script-work-in-the-terminal-but-not-from-a-file

usage="
Usage: l99 COMMAND [PARAMS]

Run a Ladder99 command.

COMMAND
    build     build a Docker image for a ladder99 service
    disk      show disk usage for current setup
    download  clone a git repo to use as current setup
    init      create a new setup folder
    logs      follow and search logs of a running or stopped service
    restart   restart services
    start     start services
    status    show status of running services
    stop      stop running services
    update    update source code for ladder99 and current setup
    use       specify setup to use with l99 commands

Run the command with -h for help on that command.

Examples
    l99 status
    l99 use example
    l99 disk
    l99 start agent
    l99 logs agent error
    l99 stop agent
    l99 update
    l99 init my-company
"

if [ "$L99_HOME" = "" ]; then
    echo "Please install the Ladder99 cli using the install script, i.e. run 'shell/install'."
    exit 1
fi

cd $L99_HOME

# show help if count of params is zero
if [ $# -eq 0 ]; then
    echo "$usage"
    shell/commands/using
    exit
fi

# get command
CMD=$1 # eg 'start'
CMD_PATH=shell/commands/$CMD # eg 'shell/commands/start'
shift

# get paramters
PARAMS=$* # eg '--offline agent'

# run command with parameters
"$CMD_PATH" $PARAMS # eg 'shell/start --offline agent'
