#!/usr/bin/env node

// replay mqtt recordings
// uses python package https://github.com/rpdswtk/mqtt_recorder

// usage: shell/replay MODEL
// where MODEL is the model folder containing a simulations folder

const fs = require('fs')
const shell = require('shelljs')

const model = process.argv[2] // eg 'ccs-pa'
const port = 1883

const folder = `models/${model}/simulations`

const csvfiles = fs
  .readdirSync(folder)
  .filter(csvfile => csvfile.endsWith('.csv'))

while (true) {
  for (const csvfile of csvfiles) {
    const cmd = `mqtt-recorder \
      --host localhost \
      --port ${port} \
      --mode replay \
      --loop false \
      --file ${folder}/${csvfile}.csv`
    console.log(cmd)
    shell.exec(cmd)
  }
}
