#!/bin/bash

# restart services

usage="
Usage: l99 restart [SERVICES]

Stop and start the specified Ladder99 services for the current setup.

See 'l99 start' for help.
"

# show help if count of params is zero
if [ $# -le 1 ]; then
    echo "$usage"
    exit 1
fi

SERVICES=$*

/bin/bash -c "l99 stop $SERVICES && l99 start $SERVICES"
