#!/bin/bash

# restart services

usage="
Usage: ./l99 restart SETUP [SERVICES]

Stop and start the specified Ladder99 services.

See './l99 start' for help.
"

# show help if count of params is zero
if [ $# -le 1 ]; then
    echo "$usage"
    exit 1
fi

SETUP=$1
shift
SERVICES=$*

/bin/bash -c "shell/linux/stop $SERVICES && shell/linux/start $SETUP $SERVICES"
