#!/bin/bash
# tapedeck - play/record mqtt messages
# specify play/record as parameter, eg
#     shell/tapedeck play
#     shell/tapedeck record

MODE=$1
FOLDER=${2:-"./recordings"}
COMPOSE=services/tapedeck/compose.yaml

# these values override the settings in docker compose.yaml
HOST=host.docker.internal \
PORT=1883 \
LOOP=true \
MODE=$MODE \
FOLDER=$FOLDER \
docker-compose --file $COMPOSE up --build tapedeck
