#!/bin/bash

usage="
Usage: ./update SETUP

Update Ladder99 pipeline and client code

SETUP        name of client or setup folder, eg oxbox or ./setups/vmc
"

# show help
if [ $# -eq 0 ]; then
    echo "$usage"
    exit 1
fi

# get setup folder
# if starts with '.' treat as a setup folder, else a client name
if [[ $1 = .* ]]; then
    SETUP=$1
else
    SETUP=../client-$1
fi

# # pull ladder99-ce repo
# CMD="git pull"
# echo $CMD
# bash -c "$CMD"

# pull ladder99-ce repo then client repo
# set credential cache while we're at it so user doesn't have to
# keep entering passcode - 360000=100h.
# do both pulls in same command so if first fails, won't do second - 
# because it was easy to miss the failed first command.
CMD="git pull && (cd $SETUP && git config credential.helper 'cache --timeout=360000' && git pull)"
echo $CMD
bash -c "$CMD"

echo Done.
