#!/bin/bash

usage="
Usage: l99 update SETUP

Update Ladder99 pipeline and client code.

SETUP        name of client or setup folder, eg demo
"

# show help
if [ $# -eq 0 ]; then
    echo "$usage"
    exit 1
fi

# get setup folder

# # if starts with '.' treat as a setup folder, else a client name
# if [[ $1 = .* ]]; then
#     SETUP=$1
# else
#     SETUP=../client-$1
# fi

# handle example setup specially
if [ $1 = example ]; then
    # SETUP=setups/example
    SETUP=$L99_HOME/setups/example
else
    # SETUP=../setup-$1
    SETUP=$L99_HOME/../setup-$1
fi
shift

# SETUP=../setup-$1
# shift


# pull ladder99-ce repo then client repo
# set credential cache while we're at it so user doesn't have to
# keep entering passcode - 360000=100h.
# do both pulls in same command so if first fails, won't do second - 
# because it was easy to miss the failed first command.
CMD="git pull && (cd $SETUP && git config credential.helper 'cache --timeout=360000' && git pull)"
echo $CMD
bash -c "$CMD"

echo Done.
