#!/bin/bash

# update Ladder99 pipeline and client code

# get setup folder

# # if starts with '.' treat as a setup folder, else a client name
# if [[ $1 = .* ]]; then
#     SETUP=$1
# else
#     SETUP=../client-$1
# fi

# # handle example setup specially
# if [ $1 = example ]; then
#     SETUP=setups/example
# else
#     SETUP=../setup-$1
# fi
# shift

SETUP=$(cat .l99_setup)

# handle missing setup folder
if [ ! -e $SETUP ]; then
    echo No setup specified - please run the \'l99 use SETUP\' command.
    echo
    exit 1
fi


# pull ladder99 repo then client repo
# set credential cache while we're at it so user doesn't have to
# keep entering passcode - 360000=100h.
# do both pulls in same command so if first fails, won't do second - 
# because it was easy to miss the failed first command.
CMD="git pull && (cd $SETUP && git config credential.helper 'cache --timeout=360000' && git pull)"
echo $CMD
bash -c "$CMD"

echo Done.
