{
 "title": "Power Consumption",
 "tags": [ "client" ],
 "time": { "from": "2022-03-08T17:29:36.175Z", "to": "2022-03-08T18:21:08.703Z" },
 "templating": {
  "list": [
   { "name": "device", "query": "f13_50,f13_100" }
  ]
 },
 "panels": [
  {
   "title": "Image",
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<!-- f13_50 -->\r\n<!-- <img src=\"https://www.teximp.com/db_data/pro/nakamura_wt-wy-03/mainimg_web.jpg\"/> -->\r\n\r\n<!-- f13_100 -->\r\n<!-- <img src=\"https://www.fanuc.co.jp/ja/product/robodrill/image/robodrillalphadib_cover.jpg\"/> -->\r\n"
   },
   "targets": [
    { "rawSql": "SELECT 'f13_50'" }
   ]
  },
  {
   "title": "Execution",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 18, "x": 4, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT time, value as \"Execution\"\nFROM get_timeline('$device', 'controller/path/execution', $__from, $__to)"
    }
   ]
  },
  {
   "title": "Instruction",
   "type": "table",
   "gridPos": { "h": 2, "w": 18, "x": 4, "y": 4 },
   "targets": [
    {
     "rawSql": "-- select value from history_all \n-- where device='$device' and path='controller/path/message' \n-- order by time desc limit 1\nselect value from get_last_value('$device', 'controller/path/message')"
    }
   ]
  },
  {
   "title": "Parts Completed",
   "type": "stat",
   "gridPos": { "h": 13, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "-- select value from history_all \n-- where device='$device' and path='controller/path/part_count-complete' \n-- order by time desc limit 1;\n-- this won't work with a specific time range, eg 2022-05-11 to 12\nselect value from get_last_value('$device', 'controller/path/part_count-complete')"
    }
   ]
  },
  {
   "title": "Accum Wattage GF",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT ss.tt as time, sum(ss.vavg) svavg from\n(\n  SELECT time_bucket_gapfill('5 minutes', time) as tt, \n    interpolate(avg(value)) vavg\n    --sum(value) vsum, \n    --locf(sum(value)) vlocf, \n    --interpolate(sum(value)) vinterpolate\n  FROM history_float\n  WHERE\n    device='$device'\n    and path like 'axes/%/wattage-actual'\n    and $__timeFilter(\"time\")\n  group by tt, path\n) ss\ngroup by time\norder by 1\n\n-- select time, value from history_float\n-- where path='axes/f13_50_p1_s1/wattage-actual'\n-- and $__timeFilter(\"time\")\n"
    }
   ]
  },
  {
   "title": "Average Wattage",
   "type": "table",
   "gridPos": { "h": 7, "w": 18, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT time_bucket_gapfill('5 minutes', time) _time, path,\n    interpolate(avg(value)) average\n    --sum(value) vsum, \n    --locf(sum(value)) vlocf, \n    --interpolate(sum(value)) vinterpolate\n  FROM history_float\n  WHERE\n    device='$device'\n    and path like 'axes/%/wattage-actual'\n    and $__timeFilter(\"time\")\n  group by _time, path\n  order by 1\n"
    }
   ]
  },
  {
   "title": "Latest",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  path,\n  time,\n  min((value->>0)::int) as value\nFROM history_all\nWHERE\n  device='$device'\n  and path like 'axes/%/wattage-actual'\n  and (path, time) in (\n    select path, max(time) from history_all\n    where time > (now() - interval '1 day')\n      and device='$device'\n    group by path\n  )\ngroup by path, time\norder by\n  path"
    }
   ]
  },
  {
   "title": "Wattage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT $__time(\"time\"), value, path\nFROM history_float\nWHERE\n  device='$device'\n  and path like 'axes/%/wattage-actual'\n  and $__timeFilter(\"time\")\norder by time asc"
    }
   ]
  },
  {
   "title": "Latest",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  path,\n  time,\n  min((value->>0)::int) as value\nFROM history_all\nWHERE\n  device='$device'\n  and path like 'axes/%/load'\n  and (path, time) in (\n    select path, max(time) from history_all\n    where time > (now() - interval '1 day')\n      and device='$device'\n    group by path\n  )\ngroup by path, time\norder by\n  path"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 4, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT $__time(\"time\"), value, path\nFROM history_float\nWHERE\n  device='$device'\n  and path like 'axes/%/load'\n  and $__timeFilter(\"time\")\norder by time asc"
    }
   ]
  }
 ]
}