version: 2
updates:
  - package-ecosystem: 'npm'
    directory: /services/adapter
    # Raise pull requests for version updates
    # to npm against the 'develop' branch
    target-branch: 'develop'
    schedule:
      interval: 'daily'
    commit-message:
      # Prefix all commit messages with "npm"
      prefix: 'npm'

  - package-ecosystem: 'npm'
    directory: /services/compiler
    target-branch: 'develop'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'npm'

  - package-ecosystem: 'npm'
    directory: /services/recorder
    target-branch: 'develop'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'npm'

  - package-ecosystem: 'npm'
    directory: /services/relay
    target-branch: 'develop'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'npm'
