version: 2
updates:
  - package-ecosystem: 'npm'
    directory: /pipeline/adapter
    target-branch: 'develop'
    schedule:
      interval: 'daily'
    commit-message:
      # Prefix all commit messages with "npm"
      prefix: 'npm'

  - package-ecosystem: 'npm'
    directory: /pipeline/compiler
    target-branch: 'develop'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'npm'

  - package-ecosystem: 'npm'
    directory: /pipeline/recorder
    target-branch: 'develop'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'npm'

  - package-ecosystem: 'npm'
    directory: /pipeline/relay
    target-branch: 'develop'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'npm'
