# modify /etc/hosts:
#
# <ip_where_this_lives> rabbitred rabbitblack nodered
#
# docker-compose stop; docker-compose rm -f; sudo rm -rf volumes; \
# git pull; docker-compose pull; docker-compose build; docker-compose up

# volume container
# tianon/true is smallest possible image - 
# see https://github.com/tianon/dockerfiles/tree/master/true
volumesx:
  image: tianon/true
  volumes:
    - "./volumes/node-red/:/root/.node-red/"
    - "./volumes/rabbitmq/lib:/var/lib/rabbitmq/"
#    - "./volumes/rabbitmq/etc:/etc/rabbitmq/"
    - "./volumes/ldap/:/var/lib/ldap"
    - "./volumes/slap/:/etc/ldap/slapd.d"

# automatic reverse proxy for exposed ports
# todo: certs for 443
proxy:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
#   - "443:443"
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock:ro"
  restart: always
  log_driver: "json-file"
  log_opt:
    max-size: "100k"
    max-file: "20"

# https://github.com/osixia/docker-openldap
ldap:
  image: osixia/openldap
  expose:
    - "389"
    - "636"
  volumes_from:
    - "volumesx"
#  environment:
#    LDAP_DOMAIN: example.com
#    LDAP_ORGANIZATION: "Example Ltd."
#    LDAP_ROOTPASS: toor

# https://github.com/osixia/docker-phpLDAPadmin
webldap:
  image: osixia/phpldapadmin
  environment:
    PHPLDAPADMIN_LDAP_HOSTS: ldap
  links:
    - ldap
    - proxy
  expose:
    - "443"
    - "80"
  ports:
    - "443:443"

# 'outside' rabbitmq
rabbitblack:
  build: rabbitmq/
  # build: rabbitmq_udp/
  restart: always
  environment:
    RABBITMQ_NODENAME: rabbitblack
    VIRTUAL_HOST: rabbitblack
    VIRTUAL_PORT: 15672
  hostname: rabbit_black
  volumes_from:
    - "volumesx"
  ports:
    - "1884:1883"
    - "5673:5672"
    - "25673:25672"
    - "1234:1234/udp"
  expose:
    - "15672"
  links:
    - proxy

# 'inside' rabbitmq
rabbitred:
  build: rabbitmq/
  restart: always
  environment:
    RABBITMQ_NODENAME: rabbitred
    VIRTUAL_HOST: rabbitred
    VIRTUAL_PORT: 15672
  hostname: rabbit_red
  volumes_from:
    - "volumesx"
  ports:
    - "1885:1883"
    - "5674:5672"
    - "25674:25672"
    - "1235:1234/udp"
  expose:
    - "15672"
  links: 
    - proxy


# and something to generate messages to rabbitblack (outside)
nodered:
  image: beevelop/node-red
  environment:
    VIRTUAL_HOST: nodered
    VIRTUAL_PORT: 1880
  expose:
    - "1880"
  volumes_from:
    - "volumesx"
  restart: always
  links:
    - rabbitblack
    - proxy

