#!/bin/bash
# build and deploy multiarch adapter docker image

# do `docker login --user ladder99` if permission denied
# do `docker buildx create --use` if error "multiple platforms not supported"
# note: the image won't show up in `docker images` because it's multiarch

# get platforms to build, with a default value
PLATFORM=${1:-'linux/amd64,linux/arm/v7,linux/arm64'}

cd services/adapter

#. get version from package.json? 
# but then has to rebuild that copy and subsequent layers.
# L99_ADAPTER_VERSION=`jq -r .version package.json`
# --tag=ladder99/adapter:$L99_ADAPTER_VERSION \

# build and deploy to hub
# note: you have to use either --push or --load. 
# --load fails for multiarch, so we have to push to a registry, docker hub. 
# initially had it pushing as :test, but then no way to add :latest to it
# after testing. 
docker buildx build \
  --platform=$PLATFORM \
  --tag=ladder99/adapter:latest \
  --push \
  .
