# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

build:
  os: ubuntu-22.04
  tools:
    python: '3.12'

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py

version: 2