#!/bin/bash

usage="
Usage: ./disk SETUP

Print disk usage for given setup

SETUP is a client name or setup folder, eg oxbox, or ./setups/vmc.
"

# show help
if [ $# -eq 0 ]; then
    echo "$usage"
    exit 1
fi

# get setup folder
# if starts with '.' treat as a setup folder, else a client name
if [[ $1 = .* ]]; then
    SETUP=$1
else
    SETUP=../client-$1
fi
shift

# also sorts alpha
# see https://stackoverflow.com/questions/46173298/how-to-sort-or-order-results-docker-ps-format/49973096#49973096
# docker container ls --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}' | (read -r; printf "%s\n" "$REPLY"; sort -k 1 )
echo
echo Disk usage
df -h /
echo
echo Setup usage
sudo du -d1 -h $SETUP/volumes/

