version: '3.7'

services:
  device:
    container_name: device
    build:
      context: .
      dockerfile: parts/device/docker/Dockerfile
    environment:
      - MQTT_HOST=broker
      - MQTT_PORT=1883
    depends_on:
      adapter:
        condition: service_started
    networks:
      - ladder99

  broker:
    container_name: broker
    image: eclipse-mosquitto
    networks:
      - ladder99
    volumes:
      - ./parts/broker/config:/mosquitto/config
      - ./parts/broker/data:/mosquitto/data
      - ./parts/broker/log:/mosquitto/log

  adapter:
    container_name: adapter
    build: parts/adapter
    environment:
      - MQTT_HOST=broker
      - MQTT_PORT=1883
      - OUTPUT_HOST=agent
      - OUTPUT_PORT=7878
      # - OUTPUT_HOST=rabbitblack
      # - OUTPUT_PORT=5673
    depends_on:
      broker:
        condition: service_started
      agent:
        condition: service_started
    networks:
      - ladder99
    volumes:
      - ./parts/adapter/config:/etc/mtconnect/adapter

  # diode:
  #   container_name: diode
  #   build:
  #     context: .
  #     dockerfile: parts/diode/docker/Dockerfile
  #   networks:
  #     - ladder99

  agent:
    container_name: agent
    build: parts/agent
    networks:
      - ladder99
    ports:
      - 5000:5000
    volumes:
      - ./parts/agent/config:/etc/mtconnect/agent
      - ./parts/agent/data:/var/lib/agent

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    logging:
      driver: 'none'
    networks:
      - ladder99
    ports:
      - '9000:9000'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
  telegraf_conf:

networks:
  ladder99:
    name: ladder99
