version: '3.7'

services:
  # broker:
  #   container_name: broker
  #   image: eclipse-mosquitto
  #   networks:
  #     - ladder99
  #   volumes:
  #     - ./etc/broker/mosquitto:/mosquitto/config
  #     - ./data/broker/mosquitto:/mosquitto/data
  #     - ./var/log/broker/mosquitto:/mosquitto/log

  # adapter:
  #   container_name: adapter
  #   build:
  #     context: .
  #     dockerfile: docker/adapter/Dockerfile
  #   environment:
  #     - MQTT_HOST=broker
  #     - MQTT_PORT=1883
  #   depends_on:
  #     broker:
  #       condition: service_started
  #   networks:
  #     - ladder99
  #   volumes:
  #     - ./etc/adapter:/etc/mtconnect/adapter

  # device:
  #   container_name: device
  #   build:
  #     context: .
  #     dockerfile: docker/device/Dockerfile
  #   environment:
  #     - MQTT_HOST=broker
  #     - MQTT_PORT=1883
  #   depends_on:
  #     adapter:
  #       condition: service_started
  #   networks:
  #     - ladder99

  diode:
    container_name: diode
    build:
      context: .
      dockerfile: docker/diode/Dockerfile
    networks:
      - ladder99

  # agent:
  #   container_name: agent
  #   image: raymondhub/mtconnect:v1.5
  #   networks:
  #     - ladder99
  #   ports:
  #     - 5000:5000
  #   volumes:
  #     - ./etc/agent:/etc/mtconnect/agent
  #     - ./data/agent:/var/lib/agent
  #   command: 'agent debug /etc/mtconnect/agent/agent.cfg'

  # portainer:
  #   container_name: portainer
  #   image: portainer/portainer-ce
  #   restart: always
  #   logging:
  #     driver: 'none'
  #   networks:
  #     - ladder99
  #   ports:
  #     - '9000:9000'
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - /etc/timezone:/etc/timezone:ro
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - portainer_data:/data

# volumes:
#   portainer_data:
#   telegraf_conf:

networks:
  ladder99:
