#!/bin/bash

# run a ladder99 shell command

usage="
Usage: l99 COMMAND [PARAMS]

Run a Ladder99 command.

COMMAND
    disk      show disk usage for a setup
    init      create a new setup folder
    list      list running services
    logs      follow and search logs of a running or stopped service
    restart   restart services
    start     start services
    stop      stop running services
    update    update source code for ladder99 and a given setup
    use       specify setup to use with l99 commands

Run the command or with -h for help on that command.

Examples
    l99 list
    l99 use example
    l99 disk
    l99 start agent
    l99 logs agent error
    l99 stop agent
    l99 update
    l99 init my-company
"

# note: this needs to run as /bin/bash, NOT /bin/sh - led to bug on encabulator
# where it wasn't parsing [[ $setup = .* ]] correctly.
# some discussion here
# https://unix.stackexchange.com/questions/379464/why-does-this-script-work-in-the-terminal-but-not-from-a-file

if [ "$L99_HOME" = "" ]; then
    echo Please install the Ladder99 cli using the install script, ie run \'install\'.
    exit 1
fi

cd $L99_HOME

# show help if count of params is zero
if [ $# -eq 0 ]; then
    echo "$usage"
    echo Current Ladder99 setup folder is \'$(cat .l99_setup)\'.
    exit 1
fi

CMD=$1 # eg 'start'
CMD_PATH=shell/$CMD # eg 'shell/start'
shift
PARAMS=$*
"$CMD_PATH" $PARAMS
