#!/bin/bash

# tail/search docker logs
# see https://stackoverflow.com/questions/34724980/finding-a-string-in-docker-logs-of-container

usage="
Usage: ./logs SERVICE [PATTERN]

Follow Docker service logs, and optionally search for a pattern using grep
"

# show help
if [ $# -eq 0 ]; then
    echo "$usage"
    exit 1
fi

SERVICE=$1
PATTERN=$2

# docker logs -t $SERVICE &2>1 | grep $PATTERN

# check if PATTERN is empty
if [ -z "$PATTERN" ]; then
    docker logs --timestamps --follow $SERVICE
else
    docker logs --timestamps --follow $SERVICE | grep -i $PATTERN
fi

# find docker service id
# ID=`docker inspect --format={{.Id}} $SERVICE`

# show service directory
# sudo ls -l /var/lib/docker/containers/$ID

# include all json log files
# sudo grep $PATTERN /var/lib/docker/containers/$ID

# open log in editor - use /<text>[ENTER] to search forward, hit n for next
# sudo vim /var/lib/docker/containers/$ID/$ID-json.log
