#!/bin/bash

# search through docker logs
# see https://stackoverflow.com/questions/34724980/finding-a-string-in-docker-logs-of-container

usage="
Usage: ./search SERVICE PATTERN

Search Docker service logs for the given pattern using grep
"

# show help
if [ $# -eq 0 ]; then
    echo "$usage"
    exit 1
fi

SERVICE=$1
PATTERN=$2

# docker logs --timestamps $SERVICE &2>1 | grep $PATTERN
docker logs --timestamps $SERVICE | grep -i $PATTERN

# find docker service id
# ID=`docker inspect --format={{.Id}} $SERVICE`

# show service directory
# sudo ls -l /var/lib/docker/containers/$ID

# include all json log files
# sudo grep $PATTERN /var/lib/docker/containers/$ID

# open log in editor - use /<text>[ENTER] to search forward, hit n for next
# sudo vim /var/lib/docker/containers/$ID/$ID-json.log
