#!/bin/bash

# search through docker logs
# see https://stackoverflow.com/questions/34724980/finding-a-string-in-docker-logs-of-container

container=$1
pattern=$2
id=`docker inspect --format={{.Id}} $container`

# show container directory
# sudo ls -l /var/lib/docker/containers/$id

# include all json log files
# sudo grep $pattern /var/lib/docker/containers/$id

# better - include timestamps
# docker logs -t $container &2>1 | grep $pattern
# eg
# docker logs -t adapter &2>1 | grep jobboss

# open log in editor - use /<text>[ENTER] to search forward, hit n for next
sudo vim /var/lib/docker/containers/$id/$id-json.log

