#!/bin/sh

# run ladder99 pipeline with docker compose.

usage="
Usage: ./start [OPTIONS] SERVICES

Run the Ladder99 pipeline with a list of services to include.

OPTIONS
  -c, --console       run the services attached to the console for logging
  -s, --setup SETUP   run the specified setup, instead of the default '../client'

SERVICES      space-delim list of profiles/services to start
  dashboard   client-specific profile - typically includes adapter, agent, 
              postgres, grafana, etc

  adapter     ladder99 adapter - converts machine language to shdr
  agent       mtconnect agent - converts shdr to xml and html (port 5000)
  grafana     ladder99 dashboard - displays database data (port 80)
  pgadmin     manages postgres database (port 5050)
  portainer   manages docker containers (port 9000)
  postgres    ladder99 database with timescaledb extension (port 5432)

Examples
    ./start dashboard
    ./start --setup ../client-oxbox dashboard
    ./start --setup setups/test/micro agent
    ./start --console play
"
#   play        play back machine data
#   record      record machine data
# Stopping
#   use './stop' to stop all profiles/services
#   use 'docker stop SERVICE' or portainer to stop individual services

# show help
if [ $# -eq 0 ]; then
    echo "$usage"
    exit 1
fi

# default values
mode=startd # detached mode
setup=../client

# get arguments
# while $1 starts with '-'
while [[ $1 = \-* ]]
do
    if [ $1 = "-c" ] || [ $1 = "--console" ]; then
        shift
        mode=start # console mode
    fi
    if [ $1 = "-s" ] || [ $1 = "--setup" ]; then
        shift
        setup=$1 # eg '../client-oxbox' or 'setups/test/micro'
        shift
    fi
done

# get services
services=$* # eg 'agent play'

# build command and call it
cmd="sh/pipeline $mode $setup $services"
echo $cmd
# bash -c "$cmd"
