#!/bin/bash

usage="
Usage: ./stop SETUP SERVICES

Stop Ladder99 services/profiles.
"
# Can also use 'docker stop SERVICE' to stop an individual service.

if [ $# -eq 0 ]; then
    echo "$usage"
    exit 1
fi

# get setup folder
# if starts with '.' treat as a setup folder, else a client name
if [[ $1 = .* ]]; then
    SETUP=$1
else
    SETUP=../client-$1
fi
shift

# get command and call it
cmd="shell/pipeline stop $setup"
echo $cmd
bash -c "$cmd"
