#!/bin/bash

# run ladder99 pipeline with docker compose.

usage="
Usage: ./stop CLIENT

Stop all Ladder99 services for the given client/setup

CLIENT     setup client or folder, eg 'myclient' or './setups/micro'

Use 'docker stop SERVICE' to stop an individual service.
"

if [ $# -eq 0 ]; then
    echo "$usage"
    exit 1
fi

# get setup folder
# if starts with '.' treat as a setup folder, else a client name
if [[ $1 = .* ]]; then
    setup=$1
else
    setup=../client-$1
fi

# get command and call it
cmd="shell/pipeline stop $setup"
echo $cmd
bash -c "$cmd"
