#!/bin/bash

# transfer a file to another host
# eg
#   ./transfer backup.sql pi 10.0.1.1

FILE=$1
USER=$2
HOST=$3

# eg scp db.sql pi@10.0.0.0:~/db.sql
sudo scp $FILE $USER@$HOST:~/$FILE

echo Done.
