#!/bin/bash

usage="
Usage: ./update SETUP

Update Ladder99 pipeline and client code

SETUP        name of client or setup folder, eg oxbox or ./setups/vmc
"

# show help
if [ $# -eq 0 ]; then
    echo "$usage"
    exit 1
fi

# get setup folder
# if starts with '.' treat as a setup folder, else a client name
if [[ $1 = .* ]]; then
    SETUP=$1
else
    SETUP=../client-$1
fi

# pull ladder99-ce repo
cmd="git pull"
echo $cmd
bash -c "$cmd"

# pull client repo
# set credential cache while we're at it so user doesn't have to
# keep entering passcode - just do it once per hour.
cmd="(cd $setup && git config credential.helper 'cache --timeout=3600' && git pull)"
echo $cmd
bash -c "$cmd"

echo Done.
