#!/bin/bash

usage="
Usage: ./update

Update Ladder99 pipeline and client code

CLIENT        name of client folder - prepended with '../client-',
              unless starts with './'
"

# # show help
# if [ $# -eq 0 ]; then
#     echo "$usage"
#     exit 1
# fi

# # get setup folder
# # if starts with '.' treat as a setup folder, else a client name
# if [[ $1 = .* ]]; then
#     setup=$1
# else
#     setup=../client-$1
# fi

# read envars, incl SETUP
source .env

# pull ladder99-ce repo
cmd="git pull"
echo $cmd
bash -c "$cmd"

# pull client repo
# set credential cache while we're at it so user doesn't have to
# keep entering passcode - just do it once per hour.
cmd="(cd $setup && git config credential.helper 'cache --timeout=3600' && git pull)"
echo $cmd
bash -c "$cmd"

echo Done.
