{
 "title": "Yetter",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "device", "label": "Device Name/UUID", "query": "select name_uuid from devices" }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT time, value as c\nFROM history_float\nWHERE\n  device='$device' and\n  property='axes/c/temperature' and\n  $__timeFilter(\"time\")"
    },
    {
     "rawSql": "SELECT time, value as x\nFROM history_float\nWHERE\n  device='$device' and\n  property='axes/x/temperature' and\n  $__timeFilter(\"time\")"
    },
    {
     "rawSql": "SELECT time, value as y\nFROM history_float\nWHERE\n  device='$device' and\n  property='axes/y/temperature' and\n  $__timeFilter(\"time\")"
    },
    {
     "rawSql": "SELECT time, value as z\nFROM history_float\nWHERE\n  device='$device' and\n  property='axes/z/temperature' and\n  $__timeFilter(\"time\")"
    },
    {
     "rawSql": "SELECT time, value as c2\nFROM history_float\nWHERE\n  device='$device' and\n  property='axes/c2/temperature' and\n  $__timeFilter(\"time\")"
    },
    {
     "rawSql": "SELECT time, value as coolant\nFROM history_float\nWHERE\n  device='$device' and\n  property='systems/coolant/temperature' and\n  $__timeFilter(\"time\")"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT time, value as c\nFROM history_float\nWHERE\n  device='$device' and\n  property='axes/c/load' and\n  $__timeFilter(\"time\")"
    },
    {
     "rawSql": "SELECT time, value as x\nFROM history_float\nWHERE\n  device='$device' and\n  property='axes/x/load' and\n  $__timeFilter(\"time\")"
    },
    {
     "rawSql": "SELECT time, value as y\nFROM history_float\nWHERE\n  device='$device' and\n  property='axes/y/load' and\n  $__timeFilter(\"time\")"
    },
    {
     "rawSql": "SELECT time, value as z\nFROM history_float\nWHERE\n  device='$device' and\n  property='axes/z/load' and\n  $__timeFilter(\"time\")"
    },
    {
     "rawSql": "SELECT time, value as c2\nFROM history_float\nWHERE\n  device='$device' and\n  property='axes/c2/load' and\n  $__timeFilter(\"time\")"
    }
   ]
  },
  {
   "title": "Timeline",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Timeline",
     "type": "natel-discrete-panel",
     "gridPos": { "h": 10, "w": 23, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT time, value as \"Availability\"\nFROM history_text\nWHERE \n  device='$device' and\n  property='availability' and $__timeFilter(\"time\")\nORDER BY time"
      },
      {
       "rawSql": "SELECT time, value as \"Rotary Mode\"\nFROM history_text\nWHERE \n  device='$device' and\n  property='axes/c/rotary-mode' and $__timeFilter(\"time\")\nORDER BY time"
      },
      {
       "rawSql": "SELECT time, value as \"Electric Power\"\nFROM history_text\nWHERE \n  device='$device' and\n  property='systems/electric/power-state' and $__timeFilter(\"time\")\nORDER BY time"
      },
      {
       "rawSql": "SELECT time, value as \"Emergency Stop\"\nFROM history_text\nWHERE \n  device='$device' and\n  property='controller/emergency-stop' and $__timeFilter(\"time\")\nORDER BY time"
      },
      {
       "rawSql": "SELECT time, value as \"Execution\"\nFROM history_text\nWHERE \n  device='$device' and\n  property='controller/path/execution' and $__timeFilter(\"time\")\nORDER BY time"
      },
      {
       "rawSql": "SELECT time, value as \"System Condition\"\nFROM history_text\nWHERE \n  device='$device' and\n  property='system-condition' and $__timeFilter(\"time\")\nORDER BY time"
      },
      {
       "rawSql": "SELECT time, value as \"Controller Mode\"\nFROM history_text\nWHERE \n  device='$device' and\n  property='controller/path/controller-mode' and $__timeFilter(\"time\")\nORDER BY time"
      }
     ]
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Path Feedrate (mm/sec)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  value\nFROM history_float\nWHERE\n  device='$device' and\n  property='controller/path/path-feedrate' and\n  $__timeFilter(\"time\")"
      }
     ]
    },
    {
     "title": "Spindle Speed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "rawSql": "SELECT time, value as Actual\nFROM history_float\nWHERE\n  device='$device' and\n  property='axes/c/spindle-speed-actual' and\n  $__timeFilter(\"time\")"
      },
      {
       "rawSql": "SELECT time, value as Override\nFROM history_float\nWHERE\n  property='axes/c/spindle-speed-override' and\n  $__timeFilter(\"time\")"
      }
     ]
    },
    {
     "title": "Commanded Position (mm)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "yaxes": [
      { "format": "lengthmm" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  value as x\nFROM history_float\nWHERE \n  device='$device' and\n  property='axes/x/position-commanded' and\n  $__timeFilter(\"time\");"
      },
      {
       "rawSql": "SELECT\n  time,\n  value as y\nFROM history_float\nWHERE \n  device='$device' and\n  property='axes/y/position-commanded' and\n  $__timeFilter(\"time\");"
      },
      {
       "rawSql": "SELECT\n  time,\n  value as z\nFROM history_float\nWHERE \n  device='$device' and\n  property='axes/z/position-commanded' and\n  $__timeFilter(\"time\");\n"
      }
     ]
    },
    {
     "title": "Actual Position (mm)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 11, "x": 11, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "yaxes": [
      { "format": "lengthmm" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  value as x\nFROM history_float\nWHERE \n  device='$device' and\n  property='axes/x/position-actual' and\n  $__timeFilter(\"time\");"
      },
      {
       "rawSql": "SELECT\n  time,\n  value as y\nFROM history_float\nWHERE \n  device='$device' and\n  property='axes/y/position-actual' and\n  $__timeFilter(\"time\");"
      },
      {
       "rawSql": "SELECT\n  time,\n  value as z\nFROM history_float\nWHERE \n  device='$device' and\n  property='axes/z/position-actual' and\n  $__timeFilter(\"time\");\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Paths",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Path 2d",
     "type": "michaeldmoore-scatter-panel",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
     "targets": [
      {
       "rawSql": "SELECT time,\n  SUM(CASE property WHEN 'axes/x/position-actual' THEN value ELSE 0 END) AS x,\n  SUM(CASE property WHEN 'axes/y/position-actual' THEN value ELSE 0 END) AS y\nFROM history_float\nWHERE \n  device='$device' and\n  $__timeFilter(\"time\")\nGROUP BY time\n;\n"
      }
     ]
    },
    {
     "title": "Path 3d",
     "type": "natel-plotly-panel",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 35 },
     "targets": [
      {
       "rawSql": "SELECT time,\n  SUM(CASE property WHEN 'axes/x/position-actual' THEN value ELSE 0 END) AS x,\n  SUM(CASE property WHEN 'axes/y/position-actual' THEN value ELSE 0 END) AS y,\n  SUM(CASE property WHEN 'axes/z/position-actual' THEN value ELSE 0 END) AS z\nFROM history_float\nWHERE \n  device='$device' and\n  $__timeFilter(\"time\")\nGROUP BY time\n;\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Events",
     "type": "table",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 12 },
     "targets": [
      {
       "rawSql": "SELECT\n  property,\n  time,\n  value\nFROM history_all\nWHERE\n  device='$device' and\n  (property LIKE 'controller%'\n  OR property IN ('availability', 'load-condition', 'message', 'functional-mode',\n  'system-condition', 'controller/emergency-stop', 'axes/c/rotary-mode')\n  )\n  AND $__timeFilter(\"time\")"
      }
     ]
    }
   ]
  }
 ]
}