FROM grafana/grafana:8.2.2

# Add plugins
ENV GF_INSTALL_PLUGINS=natel-discrete-panel,natel-plotly-panel,michaeldmoore-scatter-panel,dalvany-image-panel

# # Copy a config file from your working directory
# COPY grafana.ini /etc/grafana/grafana.ini
