#!/bin/bash

usage="
Usage: ./backup

Backup the currently running Postgres database container.
"

# show help
# if [ $# -eq 0 ]; then
if [ "$1" = "-h" ]; then
  echo "$usage"
  exit 1
fi

# set envars
SERVICE=backup
CMD=backup

# backup db
# docker exec runs a command within a container
# see https://github.com/offen/docker-volume-backup
docker exec $SERVICE $CMD

echo Done.
