#!/bin/bash

usage="
Usage: ./restore SETUP FILE

Restore a backup made with pg_dump -Fc into the current database.

WARNING: this deletes all data in the current database!

Example
    ./restore oxbox db_2022-02-26_124355.bak
"

# show help
if [ $# -eq 0 ]; then
  echo "$usage"
  exit 1
fi

# get setup folder
# if starts with '.' treat as a setup folder, else a client name
if [[ $1 = .* ]]; then
    SETUP=$1
else
    SETUP=../client-$1
fi
shift

# set envars
SERVICE=postgres
DATABASE=postgres
USER=postgres
FILE=$1 # eg backup_2022-02-26_122455.bak
FOLDER1=$SETUP/volumes/$SERVICE/backups # eg ../client-oxbox/volumes/postgres/backups
FOLDER2=/var/lib/postgresql/backups # docker volume path - defined in compose.yaml

# exit if no file
if [ ! -e "$FILE" ]; then
  echo File $FILE does not exist.
  exit 1
fi  

# move file into docker volume/folder temporarily
echo Moving $FILE into Docker volume $FOLDER1...
sudo mv $FILE $FOLDER1/

# import the database
echo Importing $FILE into $DATABASE...
# docker exec runs a command within a container $SERVICE.
# -i hooks up input
# psql runs commands on a postgres db
# note: you cannot mix SQL and psql meta-commands within a -c option -
# the best way is to use separate -c commands. 
# tried using a \\ separator in a heredoc but didn't work.
#   -c is a command
#   \c chooses a database
#   \! runs a shell command
# pg_restore imports a database
#   -Fc is custom format (a compressed archive made by pg_dump)
#   --clean drops all objects before restoring them
# note: need the pre and post restore functions, or else when you try to 
# write to a hypertable you'll get an error.
# see https://docs.timescale.com/timescaledb/latest/how-to-guides/backup-and-restore/pg-dump-and-restore
docker exec -i $SERVICE psql -U $USER -d $DATABASE --echo-queries \
  -c "\c $DATABASE" \
  -c "CREATE EXTENSION IF NOT EXISTS timescaledb;" \
  -c "SELECT timescaledb_pre_restore();" \
  -c "\! pg_restore -Fc --clean --verbose -d $DATABASE -U $USER $FOLDER2/$FILE" \
  -c "SELECT timescaledb_post_restore();"

# put backup file back
echo Moving $FILE back to original location...
sudo mv $FOLDER1/$FILE $FILE

echo Done.
