#!/bin/bash

usage="
Usage: ./transfer FILE USER HOST

Transfer a file to another host

FILE         filepath/name to transfer
USER         remote username, eg pi
HOST         remote host ip address, eg 10.0.1.1

Example:
  ./transfer backup.bak pi 10.0.1.1
"

# show help
if [ $# -eq 0 ]; then
    echo "$usage"
    exit 1
fi

FILE=$1
USER=$2
HOST=$3

# eg scp db.sql pi@10.0.0.0:~/db.sql
sudo scp $FILE $USER@$HOST:~/$FILE

echo Done.
