#!/bin/sh

# run ladder99 pipeline with docker compose.

CLIENT        name of client folder - prepended with '../client-',
              unless starts with './'

usage="
Usage: sh/start SETUP SERVICES

Run a Ladder99 setup with list of services to include.

SETUP     setup folder, eg setups/test/micro
SERVICES  space-delim list of services to start, eg agent, all

Examples

    sh/start setups/test/micro agent
    sh/start setups/test/micro all
    sh/start setups/test/print-apply all play

Note: services are referenced by their 'profile' attribute in compose.yaml.
Note: use sh/stop to stop a service.
"
# use 'docker kill SERVICE' to stop an individual service.

if [ $# -eq 0 ]; then
    echo "$usage"
    exit 1
fi

cmd=start
if [ $1 = "-d" ]; then
    shift
    cmd=startd
fi

# get arguments
setup=$1 # eg 'setups/test/micro'
shift
services=$* # eg 'agent play'

# get command and call it
cmd="sh/pipeline $cmd $setup $services"
echo $cmd
bash -c "$cmd"



    # if [ $1 = "-s" ] || [ $1 = "--setup" ]; then
    #     shift
    #     setup=$1 # eg '../client-oxbox' or 'setups/test/micro'
    #     shift
    # fi

# get setup folder
# if starts with '.' treat as a setup folder, else a client name
if [[ $1 = .* ]]; then
    setup=$1
else
    setup=../client-$1
fi
shift


# get options/arguments
# MODE=--detach
# while [[ $1 = \-* ]] # while $1 starts with '-'
# do
#     if [ $1 = "-c" ] || [ $1 = "--console" ]; then
#         shift
#         MODE=
#     fi
# done



# SERVICES=${*:-"base"} # eg 'agent', defaults to 'base'


# # build command and call it
# CMD="export SETUP=$SETUP && shell/linux/pipeline $MODE $SETUP $SERVICES"
# echo $CMD
# bash -c "$CMD"

