#!/bin/bash

# this doesn't work correctly, because docker doesn't handle profiles
# for stop, only services. so, just use 'docker stop ...' to stop services.

usage="
Usage: ./stop SETUP SERVICES

Stop Ladder99 services/profiles.
"
# Can also use 'docker stop SERVICE' to stop an individual service.

if [ $# -eq 0 ]; then
    echo "$usage"
    exit 1
fi

# get setup folder
# if starts with '.' treat as a setup folder, else a client name
if [[ $1 = .* ]]; then
    SETUP=$1
else
    SETUP=../client-$1
fi
shift

SERVICES=$*

# get command and call it
CMD="shell/pipeline stop $SETUP $SERVICES"
echo $CMD
bash -c "$CMD"
