{
 "title": "Metrics",
 "tags": [ "client" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "device",
    "query": "select path from devices order by path"
   }
  ]
 },
 "panels": [
  {
   "title": "Availability",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select time, availability\nfrom metrics\nwhere \n  device = $device -- eg 'Main/Sencon'\n  and resolution = '1min'\n  and time >= ms2timestamptz($__from) and time < ms2timestamptz($__to)\n"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select time, performance\nfrom metrics\nwhere \n  device = $device -- eg 'Main/Sencon'\n  and resolution = '1min'\n  and time >= ms2timestamptz($__from) and time < ms2timestamptz($__to)\n"
    }
   ]
  },
  {
   "title": "Quality",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select time, quality\nfrom metrics\nwhere \n  device = $device -- eg 'Main/Sencon'\n  and resolution = '1min'\n  and time >= ms2timestamptz($__from) and time < ms2timestamptz($__to)\n"
    }
   ]
  },
  {
   "title": "OEE",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select time, oee\nfrom metrics\nwhere \n  device = $device -- eg 'Main/Sencon'\n  and resolution = '1min'\n  and time >= ms2timestamptz($__from) and time < ms2timestamptz($__to)\n"
    }
   ]
  }
 ]
}