#!/bin/bash
# run sql command file on db
# usage:
#   source .env
#   sh/db/run setups/pi/migrations/000-init.sql

SQL_FILE=$1

cat $SQL_FILE | docker run -i --rm postgres:13 sh -c \
    "export PGPASSWORD=$PGPASSWORD && psql -h $PGHOST -p $PGPORT -d $PGDATABASE -U $PGUSER"
