#!/bin/sh

# initialize a setup

usage="
Usage: sh/init SETUP

Initialize a Ladder99 setup.

SETUP     setup subfolder, eg vmc, ccs-pa
"

if [ $# -eq 0 ]; then
    echo "$usage"
    exit 1
fi

#. mkdir
#. create minimal setup.yaml
#. create minimal pipeline-overrides.yaml - or let adapter compile it?
#. create minimal volumes/agent/agent.cfg and devices.xml - xml can't be empty

