#!/bin/sh

# run pipeline with docker run.
# use when docker-compose is not available, as used in sh/pipeline.
# runs broker, adapter, agent, recorder, and portainer services.
# examples:
#   sh/run
#   sh/run ccs-pa ladder99

SETUP=${1:-"ccs-pa"}
NETWORK=${2:-"host"}
shift
shift
SERVICES=${*:-"portainer broker adapter agent recorder"}
MODEL=ccs-pa
MODE=play

RUN="docker run -dit --init --rm --log-opt max-size=1m --log-opt max-file=5"

for service in $SERVICES
do
  echo "Starting $service..."

  if [ $service = "portainer" ]; then
    $RUN --name portainer -p 9999:9000 \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -v portainer_data:/data \
      portainer/portainer-ce
  fi

  if [ $service = "broker" ]; then
    $RUN --name broker --network $NETWORK -p 1883 -p 9001 \
      -v $(pwd)/setups/$SETUP/volumes/broker:/mosquitto \
      eclipse-mosquitto
  fi

  if [ $service = "adapter" ]; then
    docker build --tag ladder99/adapter:latest pipeline/adapter
    $RUN --name adapter --network $NETWORK \
      -v $(pwd)/setups/$SETUP:/data/setup \
      -v $(pwd)/models:/data/models \
      ladder99/adapter:latest
  fi

  if [ $service = "agent" ]; then
    $RUN --name agent --network $NETWORK -p 5000 \
      -v $(pwd)/setups/$SETUP/volumes/agent:/data/agent:rw \
      ladder99/agent:latest \
      agent debug /data/agent/agent.cfg
  fi

  if [ $service = "recorder" ]; then
    docker build --tag ladder99/recorder:latest pipeline/recorder
    $RUN --name recorder --network $NETWORK \
      -v $(pwd)/models:/data/models \
      ladder99/recorder:latest \
      recorder --mode $MODE --host localhost --folder /data/models/$MODEL/recorder
  fi

  echo ""
done
