#!/bin/sh

# run ladder99 pipeline with docker compose.

usage="
Usage: sh/start SETUP SERVICES

Run a Ladder99 setup with list of services to include.

SETUP     setup subfolder, eg vmc, ccs-pa
SERVICES  space-delim list of services to start, eg agent, all

Examples

    sh/start ccs-pa agent
    sh/start ccs-pa all
    sh/start ccs-pa all play

Note: services are referenced by their 'profile' attribute in pipeline.yaml.
Note: use sh/stop to stop a service.
"
# use 'docker kill SERVICE' to stop an individual service.

if [ $# -eq 0 ]; then
    echo "$usage"
    exit 1
fi

cmd=start
if [ $1 = "-d" ]; then
    shift
    cmd=startd
fi

# get arguments
setup=$1 # eg 'ccs-pa'
shift
services=$* # eg 'agent play'

# get command and call it
cmd="sh/pipeline $cmd $setup $services"
echo $cmd
bash -c "$cmd"
