#!/bin/sh

# run ladder99 pipeline with docker compose.

usage="
Usage: sh/stop SETUP SERVICES

Stop Ladder99 setup service(s)

SETUP     setup subfolder, eg test/micro
SERVICES  space-delim list of services to stop, eg agent, all

Examples

    sh/stop test/micro agent
    sh/stop test/micro all

Note: services are referenced by their 'profile' attribute in pipeline.yaml.
Note: cal also use 'docker kill SERVICE' to stop an individual service.
"

if [ $# -eq 0 ]; then
    echo "$usage"
    exit 1
fi

# get arguments
setup=$1 # eg 'ccs-pa'
shift
services=$* # eg 'agent play'

# get command and call it
cmd="sh/pipeline stop $setup $services"
echo $cmd
bash -c "$cmd"
