#
# modify /etc/hosts:
#
# <ip_where_this_lives> rabbitred rabbitblack nodered
#
# docker-compose stop; docker-compose rm -f; sudo rm -rf volumes; git pull; docker-compose pull; docker-compose build; docker-compose up

# experimental volume container
volumes:
  image: tianon/true
  volumes:
    - "./volumes/node-red/:/root/.node-red/"
    - "./volumes/rabbitmq/:/var/lib/rabbitmq/"
    - "./volumes/ldap/:/var/lib/ldap/"
    - "./volumes/sdap/:/etc/ldap/slapd.d/"

# automatic reverse proxy for exposed ports
proxy:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock:ro"
  restart: always

# https://github.com/osixia/docker-openldap
ldap:
  image: osixia/openldap
  expose:
    - "389"
    - "636"
  volumes_from:
    - "volumes"
  environment:
    LDAP_DOMAIN: example.com
    LDAP_ORGANIZATION: "Example Ltd."
    LDAP_ROOTPASS: toor

# https://github.com/osixia/docker-phpLDAPadmin
webldap:
  image: osixia/phpldapadmin
  expose:
    - "443:443"
  environment:
    PHPLDAPADMIN_LDAP_HOSTS: ldap
  links:
    - ldap

# 'outside' rabbitmq
rabbitblack:
  build: rabbitmq_udp/
  environment:
    RABBITMQ_NODENAME: rabbitblack
    VIRTUAL_HOST: rabbitblack
    VIRTUAL_PORT: 15672
  hostname: rabbit_black
  volumes_from:
    - "volumes"
  ports:
    - "1884:1883"
    - "5673:5672"
    - "25673:25672"
    - "1234:1234/udp"
  expose:
    - "15672"

# 'inside' rabbitmq
rabbitred:
  build: rabbitmq_udp/
  environment:
    RABBITMQ_NODENAME: rabbitred
    VIRTUAL_HOST: rabbitred
    VIRTUAL_PORT: 15672
  hostname: rabbit_red
  volumes_from:
    - "volumes"
  ports:
    - "1885:1883"
    - "5674:5672"
    - "25674:25672"
    - "1235:1234/udp"
  expose:
    - "15672"

# and something to generate messages to rabbitblack (outside)
nodered:
  image: beevelop/node-red
  environment:
    VIRTUAL_HOST: nodered
    VIRTUAL_PORT: 1880
  expose:
    - "1880"
  volumes_from:
    - "volumes"
  restart: always
  links:
    - rabbitblack

