#!/bin/bash

# compile a setup's config/setup.yaml to agent.xml etc

SETUP=$1  # setup folder, eg 'setups/print-apply'

node services/compiler/src/compile-xml.js \
  $SETUP/setup.yaml \
  $SETUP/volumes/agent/agent.xml

# # compile-xml and compile-compose
# compile SETUP='setups/demo':
#     just compile-xml {{SETUP}}
#     just compile-compose {{SETUP}}

# # compile agent.xml from model setup.yaml
# compile-xml SETUP='setups/demo':
#     node services/compiler/src/compile-xml.js \
#     {{SETUP}}/setup.yaml \
#     {{SETUP}}/volumes/agent/agent.xml

# # compile docker-compose.yaml from setup.yaml
# compile-compose SETUP='demo':
#     echo todo
