# docker-compose overrides
# overrides and extends the values in ladder99/services/compose.yaml

# see other client repos for ideas for adding information to services.
# typically, would add 'profiles: - base' to each service used.
# that way, we know what is needed, and can start them all with
#   ./l99 start <setup>
# which runs the 'base' profile by default.

# version must be a string - need 3.8 for profiles
version: '3.8'

services:
  adapter:
    # note: must specify build OR image here.
    build: ./adapter # use ladder99/services/adapter/Dockerfile
    profiles:
      - base
  agent:
    profiles:
      - base
  dozzle:
    profiles:
      - base
  grafana:
    profiles:
      - base
  # meter:
  #   profiles:
  #     - base
  portainer:
    profiles:
      - base
  postgres:
    profiles:
      - base
  pgadmin:
    profiles:
      - base
  relay:
    # note: must specify build OR image here.
    build: ./relay # use ladder99/services/relay/Dockerfile
    profiles:
      - base
  # simulation:
  #   profiles:
  #     - base
