#!/bin/bash
# install node dependencies

npm --prefix services/adapter install
npm --prefix services/compiler install
npm --prefix services/meter install
npm --prefix services/recorder install
npm --prefix services/relay install

# npm --prefix services/diode/code/application/datadiode/contrib/nodejs install
