{
 "title": "DataItems",
 "tags": [ "client" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "device", "query": "select uid from devices" },
   {
    "name": "path",
    "query": "select path from dataitems where props->>'contextPath'='$device' order by path"
   }
  ]
 },
 "panels": [
  {
   "title": "Current values for all paths",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "DataItems (last known values)",
     "type": "table",
     "gridPos": { "h": 9, "w": 23, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT \n  path,\n  time,\n  min(value->>0) as value -- just pick one of the values - should be the same\nFROM history_all\nWHERE\n  device='$device'\n  -- and $__timeFilter(\"time\")\n  and (path, time) in (\n    select path, max(time) from history_all \n    where time > (now() - interval '1 day')\n      and device='$device'\n    group by path\n  )\ngroup by path, time -- need this to eliminate duplicate records\norder by\n  path"
      }
     ]
    }
   ]
  },
  {
   "title": "Recent values for all paths",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "DataItems (recent changes)",
     "type": "table",
     "gridPos": { "h": 9, "w": 23, "x": 0, "y": 2 },
     "targets": [
      {
       "rawSql": "select path, time, value->>0 as value\nfrom history_all\nwhere\n  device='$device'\norder by time desc\nlimit 200"
      }
     ]
    }
   ]
  },
  {
   "title": "Recent values for selected path",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "DataItems (recent changes)",
     "type": "table",
     "gridPos": { "h": 9, "w": 23, "x": 0, "y": 3 },
     "targets": [
      {
       "rawSql": "select path, time, value->>0 as value\nfrom history_all\nwhere\n  device='$device'\n  and path='$path'\norder by time desc\nlimit 200"
      }
     ]
    }
   ]
  },
  {
   "title": "Plot of recent values",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "$path",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "rawSql": "select time, value\nfrom history_float\nwhere path='$path'\nand $__timeFilter(time)\norder by time\n-- limit 100\n"
      }
     ]
    }
   ]
  }
 ]
}