{
 "title": "Microcontroller",
 "tags": [ "client" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "device", "query": "Main/Micro" }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT time, value as total\nFROM history_float\nWHERE\n  path='$device/CpuTotal'\n  and $__timeFilter(\"time\")\nORDER BY time"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT time, value as temp\nFROM history_float\nWHERE\n  path='$device/Temperature'\n  and $__timeFilter(\"time\")\nORDER BY time"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT time, value as available\nFROM history_float\nWHERE\n  path = '$device/DiskAvailable'\n  and $__timeFilter(\"time\")\nORDER BY time"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT time, value as free\nFROM history_float\nWHERE\n  path='$device/MemoryFree'\n  and $__timeFilter(\"time\")\nORDER BY time"
    },
    {
     "rawSql": "SELECT time, value as used\nFROM history_float\nWHERE\n  path='$device/MemoryUsed'\n  and $__timeFilter(\"time\")\nORDER BY time"
    }
   ]
  },
  {
   "title": "Help",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Help",
     "type": "text",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
     "options": {
      "content": "## Microcontroller\n\nThe microcontroller consolidates data from factory devices, \nstores it in a database, and provides it to the dashboard here.\n\nThese charts show the status of the microcontroller itself - \nmemory free and used, CPU usage, and temperature. \n\nTemperature is typically around 40 degrees Celsius - the max is around 80. \n"
     },
     "targets": [
      { "rawSql": "SELECT 1" }
     ]
    }
   ]
  }
 ]
}