#. switched from this to using prebuilt node image - faster docker-compose

FROM node

WORKDIR /home/node/app

# install javascript dependencies
COPY package*.json ./
RUN npm ci --production

# install source
COPY src ./src

# default command on run container
CMD ["node", "src/adapter.js"]

# this causes permission denied error when connecting to agent
# USER node
