#!/bin/bash
# list contents of a docker named volume
# usage:
#   shell/docker/ls agent
#   shell/docker/ls agent styles
# source: https://www.freshblurbs.com/blog/2017/04/16/inspect-docker-volumes-on-mac.html

VOLUME=$1
SUFFIX=$2

shell/docker/vm ls -l /docker/var/lib/docker/volumes/$VOLUME/_data/$SUFFIX
