#!/bin/sh

# run pipeline with docker run.
# use when docker-compose is not available, as used in shell/pipeline.
# runs mosquitto, adapter, agent, recorder, and portainer services.
# usage:
#   shell/docker/run [SETUP [NETWORK]]
# examples:
#   shell/docker/run
#   shell/docker/run setups/print-apply ladder99

# SETUP=${1:-"setups/print-apply"}
# NETWORK=${2:-"host"}
# shift
# shift
# SERVICES=${*:-"portainer mosquitto adapter agent recorder"}
SETUP=setups/print-apply
NETWORK=host
SERVICES=portainer mosquitto adapter agent
SCHEMA=print-apply
MODE=play

RUN="docker run -dit --init --rm --log-opt max-size=1m --log-opt max-file=5"

for service in $SERVICES
do
  echo "Starting $service..."

  if [ $service = "portainer" ]; then
    $RUN --name portainer -p 9999:9000 \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -v portainer_data:/data \
      portainer/portainer-ce
  fi

  if [ $service = "mosquitto" ]; then
    $RUN --name mosquitto --network $NETWORK -p 1883 -p 9001 \
      -v $(pwd)/$SETUP/volumes/mosquitto:/mosquitto \
      eclipse-mosquitto
  fi

  if [ $service = "adapter" ]; then
    #docker build --tag ladder99/adapter:latest services/adapter
    $RUN --name adapter --network $NETWORK \
      -v $(pwd)/$SETUP:/data/setup \
      -v $(pwd)/schemas:/data/schemas \
      --pull always \
      ladder99/adapter:latest
  fi

  if [ $service = "agent" ]; then
    $RUN --name agent --network $NETWORK -p 5000 \
      -v $(pwd)/$SETUP/volumes/agent:/data/agent:rw \
      --pull always \
      ladder99/agent:latest \
      agent debug /data/agent/agent.cfg
  fi

  if [ $service = "recorder" ]; then
    docker build --tag ladder99/recorder:latest services/recorder
    $RUN --name recorder --network $NETWORK \
      -v $(pwd)/schemas:/data/schemas \
      ladder99/recorder:latest \
      recorder --mode $MODE --host localhost --folder /data/schemas/$SCHEMA/recordings
  fi

  echo ""
done
