{
 "title": "CCS P&A",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "Device",
    "query": "select nodes.props->>'uuid' as device from nodes where nodes.props->>'type'='Device'"
   }
  ]
 },
 "panels": [
  {
   "title": "Device",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  ARRAY_POSITION(array['UNAVAILABLE','AVAILABLE'], value) as pos\nFROM history_text \nWHERE device='${device}' AND property='availability'\nORDER BY time"
      }
     ]
    },
    {
     "title": "Functional Mode",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  ARRAY_POSITION(array['UNAVAILABLE','PRODUCTION','MAINTENANCE'], value) as pos\nFROM history_text \nWHERE device='${device}' AND property='functional-mode'\nORDER BY time"
      }
     ]
    },
    {
     "title": "Condition",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  ARRAY_POSITION(array['UNAVAILABLE','NORMAL', 'WARNING', 'FAULT'], value) as pos\nFROM history_text \nWHERE device='${device}' AND property='system-condition'\nORDER BY time"
      }
     ]
    },
    {
     "title": "Stats",
     "type": "table",
     "gridPos": { "h": 4, "w": 8, "x": 12, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT\n  'Message' as name,\n  value\nFROM history_text \nWHERE device='${device}' AND property='message'\nORDER BY time DESC\nLIMIT 1"
      },
      {
       "rawSql": "SELECT\n  'Firmware Version' as name,\n  value\nFROM history_text\nWHERE device='${device}' AND property='firmware-version'\nORDER BY time DESC\nLIMIT 1"
      }
     ]
    }
   ]
  },
  { "title": "Controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Emergency Stop",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ARRAY_POSITION(array['UNAVAILABLE','ARMED','TRIGGERED'], value) as pos\nFROM history_text \nWHERE device='${device}' AND property='controller/emergency-stop'\nORDER BY time"
    }
   ]
  },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ARRAY_POSITION(array['UNAVAILABLE','PROGRAM_STOPPED', 'WAIT', 'ACTIVE'], value) as pos\nFROM history_text \nWHERE device='${device}' AND property='controller/path/execution'\nORDER BY time"
    }
   ]
  },
  {
   "title": "Wait State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ARRAY_POSITION(array['UNAVAILABLE','PAUSING','RESUMING'], value) as pos\nFROM history_text \nWHERE device='${device}' AND property='controller/path/wait-state'\nORDER BY time"
    }
   ]
  },
  {
   "title": "Program",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  'Program' as name,\n  value\nFROM history_text \nWHERE device='${device}' AND property='controller/path/program-main'\nORDER BY time DESC\nLIMIT 1"
    },
    {
     "rawSql": "SELECT\n  'Step' as name,\n  value\nFROM history_text \nWHERE device='${device}' AND property='controller/path/block'\nORDER BY time DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Clocks",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  'Clock Time' as name,\n  value\nFROM history_float \nWHERE device='${device}' \nAND property like 'controller/path/clock-time'\nORDER BY time desc\nLIMIT 1"
    },
    {
     "rawSql": "SELECT\n  'Up Time' as name,\n  value\nFROM history_float \nWHERE device='${device}' \nAND property like 'controller/path/equipment-timer-operating'\nORDER BY time desc\nLIMIT 1"
    },
    {
     "rawSql": "SELECT\n  'Cycle Time' as name,\n  value\nFROM history_float \nWHERE device='${device}' \nAND property like 'controller/path/process-timer-process'\nORDER BY time desc\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Counts",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  'Cycle Count' as name,\n  value\nFROM history_float \nWHERE device='${device}' AND property like 'controller/path/count-cycle'\nORDER BY time desc\nLIMIT 1"
    },
    {
     "rawSql": "SELECT\n  'Life Count' as name,\n  value\nFROM history_float \nWHERE device='${device}' AND property like 'controller/path/count-life'\nORDER BY time desc\nLIMIT 1"
    },
    {
     "rawSql": "SELECT\n  'Fault Count' as name,\n  value\nFROM history_float \nWHERE device='${device}' AND property like 'controller/path/count-fault'\nORDER BY time desc\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Effector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true
  },
  {
   "title": "Feeder",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Print Signal Time",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  value\nFROM history_float\nWHERE device='${device}' AND property='systems/feeder/equipment-timer-delay'\nand $__timeFilter(\"time\")\norder by time\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Meta",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Events",
     "type": "table",
     "gridPos": { "h": 9, "w": 18, "x": 0, "y": 10 },
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  property,\n  value\nFROM history_all\nWHERE device='${device}' AND \n  $__timeFilter(\"time\")\nORDER BY time desc"
      }
     ]
    }
   ]
  }
 ]
}