{
 "title": "Device",
 "time": { "from": "now-3m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "device", "label": "Device", "query": "select name_uuid from devices" }
  ]
 },
 "panels": [
  { "title": "Timeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Timeline",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT time, value as \"Part Detect\"\nFROM history_text\nWHERE \ndevice='$device' and\nproperty='systems/feeder/part-detect' and $__timeFilter(\"time\")\nORDER BY time"
    },
    {
     "rawSql": "SELECT time, value as \"System Condition\"\nFROM history_text\nWHERE \ndevice='$device' and\nproperty='system-condition' and $__timeFilter(\"time\")\nORDER BY time"
    },
    {
     "rawSql": "SELECT time, value as \"Feeder\"\nFROM history_text\nWHERE device='$device' and\nproperty='systems/feeder/actuator-state-start' and $__timeFilter(\"time\")\nORDER BY time"
    },
    {
     "rawSql": "SELECT time, value as \"Emergency Stop\"\nFROM history_text\nWHERE device='$device' and\nproperty='controller/emergency-stop' and $__timeFilter(\"time\")\nORDER BY time"
    },
    {
     "rawSql": "SELECT time, value as \"Functional Mode\"\nFROM history_text\nWHERE device='$device' and\nproperty='functional-mode' and $__timeFilter(\"time\")\nORDER BY time"
    },
    {
     "rawSql": "SELECT time, value as \"Execution State\"\nFROM history_text\nWHERE device='$device' and\nproperty='controller/path/execution' and $__timeFilter(\"time\")\nORDER BY time"
    }
   ]
  },
  {
   "title": "Device",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  ARRAY_POSITION(array['UNAVAILABLE','AVAILABLE'], value) as pos\nFROM history_text \nWHERE device='${device}' AND property='availability'\nORDER BY time DESC\nLIMIT 1"
      }
     ]
    },
    {
     "title": "Functional Mode",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  ARRAY_POSITION(array['UNAVAILABLE','MAINTENANCE','PRODUCTION'], value) as pos\nFROM history_text \nWHERE device='${device}' AND property='functional-mode'\nORDER BY time desc\nlimit 1"
      }
     ]
    },
    {
     "title": "Condition",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  ARRAY_POSITION(array['UNAVAILABLE','NORMAL', 'WARNING', 'FAULT'], value) as pos\nFROM history_text \nWHERE device='${device}' AND property='system-condition'\nORDER BY time desc\nlimit 1 "
      }
     ]
    },
    {
     "title": "Stats",
     "type": "table",
     "gridPos": { "h": 4, "w": 8, "x": 12, "y": 11 },
     "targets": [
      {
       "rawSql": "SELECT\n  'Message' as name,\n  value\nFROM history_text \nWHERE device='${device}' AND property='message'\nORDER BY time DESC\nLIMIT 1"
      },
      {
       "rawSql": "SELECT\n  'Firmware Version' as name,\n  value\nFROM history_text\nWHERE device='${device}' AND property='firmware-version'\nORDER BY time DESC\nLIMIT 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Emergency Stop",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  ARRAY_POSITION(array['UNAVAILABLE','ARMED','TRIGGERED'], value) as pos\nFROM history_text \nWHERE device='${device}' AND property='controller/emergency-stop'\nORDER BY time "
      }
     ]
    },
    {
     "title": "Execution State",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  ARRAY_POSITION(array['UNAVAILABLE','PROGRAM_STOPPED', 'WAIT', 'ACTIVE'], value) as pos\nFROM history_text \nWHERE device='${device}' AND property='controller/path/execution'\nORDER BY time "
      }
     ]
    },
    {
     "title": "Program",
     "type": "table",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\n  'Program' as name,\n  value\nFROM history_text \nWHERE device='${device}' AND property='controller/path/program-main'\nORDER BY time DESC\nLIMIT 1"
      },
      {
       "rawSql": "SELECT\n  'Step' as name,\n  value\nFROM history_text \nWHERE device='${device}' AND property='controller/path/block'\nORDER BY time DESC\nLIMIT 1"
      }
     ]
    },
    {
     "title": "Clocks",
     "type": "table",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
     "targets": [
      {
       "rawSql": "SELECT\n  'Clock Time' as name,\n  value\nFROM history_float \nWHERE device='${device}' \nAND property like 'controller/path/clock-time'\nORDER BY time desc\nLIMIT 1"
      },
      {
       "rawSql": "SELECT\n  'Up Time' as name,\n  value\nFROM history_float \nWHERE device='${device}' \nAND property like 'controller/path/equipment-timer-operating'\nORDER BY time desc\nLIMIT 1"
      },
      {
       "rawSql": "SELECT\n  'Cycle Time' as name,\n  value\nFROM history_float \nWHERE device='${device}' \nAND property like 'controller/path/process-timer-process'\nORDER BY time desc\nLIMIT 1"
      }
     ]
    },
    {
     "title": "Counts",
     "type": "table",
     "gridPos": { "h": 5, "w": 7, "x": 8, "y": 7 },
     "targets": [
      {
       "rawSql": "SELECT\n  'Cycle Count' as name,\n  value\nFROM history_float \nWHERE device='${device}' AND property like 'controller/path/count-cycle'\nORDER BY time desc\nLIMIT 1"
      },
      {
       "rawSql": "SELECT\n  'Life Count' as name,\n  value\nFROM history_float \nWHERE device='${device}' AND property like 'controller/path/count-life'\nORDER BY time desc\nLIMIT 1"
      },
      {
       "rawSql": "SELECT\n  'Fault Count' as name,\n  value\nFROM history_float \nWHERE device='${device}' AND property like 'controller/path/count-fault'\nORDER BY time desc\nLIMIT 1"
      }
     ]
    }
   ]
  },
  { "title": "Effector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Feeder",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Print Signal Time",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  value\nFROM history_float\nWHERE device='${device}' AND property='systems/feeder/equipment-timer-delay'\nand $__timeFilter(\"time\")\norder by time desc\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Meta",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Events",
     "type": "table",
     "gridPos": { "h": 9, "w": 18, "x": 0, "y": 6 },
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  property,\n  value\nFROM history_all\nWHERE device='${device}' AND \n  $__timeFilter(\"time\")\nORDER BY time desc"
      }
     ]
    }
   ]
  }
 ]
}