# helloworld dockerfile

# base image - ubuntu has linux/arm/v7, linux/amd64, etc
FROM ubuntu:21.04 AS compile

# default command - can override with docker run or docker-compose command.
CMD [ "echo", "hello world!"]
