{
 "title": "Paths",
 "tags": [ "client" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "device", "label": "Device", "query": "select name from devices" }
  ]
 },
 "panels": [
  {
   "title": "Position (mm)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "yaxes": [
    { "format": "lengthmm" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  value as x\nFROM history_float\nWHERE \n  device='$device' and\n  -- path='axes/x/position-actual-machine' and\n  path in ('axes/x/position-actual','axes/x/position-actual-machine') and\n  $__timeFilter(\"time\");"
    },
    {
     "rawSql": "SELECT\n  time,\n  value as y\nFROM history_float\nWHERE \n  device='$device' and\n  --path='axes/y/position-actual-machine' and\n  path in ('axes/y/position-actual','axes/y/position-actual-machine') and\n  $__timeFilter(\"time\");"
    },
    {
     "rawSql": "SELECT\n  time,\n  value as z\nFROM history_float\nWHERE \n  device='$device' and\n  --path='axes/z/position-actual-machine' and\n  path in ('axes/z/position-actual','axes/z/position-actual-machine') and\n  $__timeFilter(\"time\");\n"
    }
   ]
  },
  {
   "title": "Path 2d",
   "type": "michaeldmoore-scatter-panel",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('sec', time) as _time,\n  avg(CASE path WHEN 'axes/x/position-actual' THEN value ELSE 0 END) AS x,\n  avg(CASE path WHEN 'axes/y/position-actual' THEN value ELSE 0 END) AS y\nFROM history_float\nWHERE\n  device='$device' and\n  $__timeFilter(\"time\")\nGROUP BY _time\n;\n"
    }
   ]
  },
  {
   "title": "Path 3d",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('sec', time) as tt,\n  SUM(CASE path WHEN 'axes/x/position-actual' THEN value ELSE 0 END) AS x,\n  SUM(CASE path WHEN 'axes/y/position-actual' THEN value ELSE 0 END) AS y,\n  SUM(CASE path WHEN 'axes/z/position-actual' THEN value ELSE 0 END) AS z\nFROM history_float\nWHERE \n  device='$device' and\n  $__timeFilter(\"time\")\nGROUP BY tt\n;\n"
    }
   ]
  }
 ]
}