# docker-compose overrides for development pipeline.

version: '3.8'

services:
  # we're using this to develop the agent html output
  agent:
    volumes:
      - ./$SETUP/volumes/agent:/data/agent # has ccs-pa agent.cfg, devices.xml
      - ../services/agent/styles-future:/data/styles

networks:
  ladder99:
    name: ladder99
