#!/bin/sh

# run pipeline with docker run.
# use when docker-compose is not available, as used in sh/pipeline.
# runs mosquitto, adapter, agent, recorder, and portainer services.
# usage:
#   sh/docker/run [SETUP [NETWORK [SERVICES]]]
# examples:
#   sh/docker/run
#   sh/docker/run test/print-apply ladder99

SETUP=${1:-"test/print-apply"}
NETWORK=${2:-"host"}
shift
shift
SERVICES=${*:-"portainer mosquitto adapter agent recorder"}
MODULE=print-apply
MODE=play

RUN="docker run -dit --init --rm --log-opt max-size=1m --log-opt max-file=5"

for service in $SERVICES
do
  echo "Starting $service..."

  if [ $service = "portainer" ]; then
    $RUN --name portainer -p 9999:9000 \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -v portainer_data:/data \
      portainer/portainer-ce
  fi

  if [ $service = "mosquitto" ]; then
    $RUN --name mosquitto --network $NETWORK -p 1883 -p 9001 \
      -v $(pwd)/setups/$SETUP/volumes/mosquitto:/mosquitto \
      eclipse-mosquitto
  fi

  if [ $service = "adapter" ]; then
    docker build --tag ladder99/adapter:latest pipeline/adapter
    $RUN --name adapter --network $NETWORK \
      -v $(pwd)/setups/$SETUP:/data/setup \
      -v $(pwd)/modules:/data/modules \
      ladder99/adapter:latest
  fi

  if [ $service = "agent" ]; then
    $RUN --name agent --network $NETWORK -p 5000 \
      -v $(pwd)/setups/$SETUP/volumes/agent:/data/agent:rw \
      ladder99/agent:latest \
      agent debug /data/agent/agent.cfg
  fi

  if [ $service = "recorder" ]; then
    docker build --tag ladder99/recorder:latest pipeline/recorder
    $RUN --name recorder --network $NETWORK \
      -v $(pwd)/modules:/data/modules \
      ladder99/recorder:latest \
      recorder --mode $MODE --host localhost --folder /data/modules/$MODULE/recordings
  fi

  echo ""
done
