{
 "title": "VMC",
 "description": "Vertical Machining Center (VMC) Dashboard",
 "time": { "from": "2021-05-26T15:19:56.699Z", "to": "2021-05-26T15:21:07.157Z" },
 "panels": [
  {
   "title": "Commanded Position (mm)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "yaxes": [
    { "format": "lengthmm" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  id,\n  value::text::numeric\nFROM \"values\"\nWHERE\n  (id='x3' or id='y3') and\n  $__timeFilter(\"time\")\nORDER BY id, time"
    }
   ]
  },
  {
   "title": "Actual Position (mm)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "yaxes": [
    { "format": "lengthmm" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time),\n  id,\n  value::text::numeric\nFROM\n  values\nWHERE\n  (id='x2' OR id='y2' OR id='z2') AND\n  $__timeFilter(time)\nORDER BY id, time"
    }
   ]
  },
  {
   "title": "Path Feedrate (mm/sec)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "yaxes": [
    { "format": "lengthmm" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  id,\n  value::text::numeric\nFROM \"values\"\nWHERE\n  id='Frt' and\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  }
 ]
}