# docker-compose overrides for vmc pipeline

version: '3.8'

services:
  agent:
    working_dir: /etc/mtconnect/simulator
    command: agent debug
    # nowork - hangs
    # command: |
    #   /usr/bin/ruby /etc/mtconnect/simulator/run_scenario.rb -l \
    #   /etc/mtconnect/simulator/VMC-3Axis-Log.txt & \
    #   cd /etc/mtconnect/simulator && agent debug agent.cfg

networks:
  ladder99:
    name: ladder99
