# docker-compose overrides for vmc pipeline

version: '3.8'

services:
  agent:
    working_dir: /etc/mtconnect/simulator
    # nowork - hangs
    # command: /usr/bin/ruby run_scenario.rb -l VMC-3Axis-Log.txt & agent debug agent.cfg

networks:
  ladder99:
    name: ladder99
