# setup.yaml
# this defines the devices.xml structure, along with the model yamls.
# read by services/adapter/src/adapter.js.
# sources define the inputs to the cache.
# compiled by services/adapter/compiler into devices.xml.
#. see also future/setup-future.yaml for future dev.

#. could have meta: section also

#. could we get this to one line per device? a site might have dozens of machines
# eg set defaults for all devices at the top, overrides per device?

devices:
  # - id: ccs-pa # this is substituted into the model yaml and sources
  - id: pa1 # this is substituted into the model yaml and sources
    #. call this 'structure: ccs-pa' ?
    model: ccs-pa # for xml structure - see models/ccs-pa/device.yaml
    #. shift these up, look for each explicitly
    properties: # these are substituted into the model yaml
      uuid: e05363af
      serialNumber: '001'

    # define data sources that feed into this device
    sources:
      - model: ccs-pa # model defines inputs and outputs with yaml files
        protocol: mqtt-json # type of plugin - manages protocol and payload
        # url: mqtt://broker:1883 #. pass in somehow - envar?
        url: mqtt://localhost:1883

      - model: rockwell-hmi
        protocol: opc
        url: opc.tcp://simulator-opc:4334/UA/LittleServer

    destinations: # where to post output - just handles one output for now
      - protocol: shdr
        # host: adapter #. pass in somehow - envar?
        host: localhost
        port: 7878
