#!/bin/bash

#. get service version from package.json - use jq to extract?

usage="
Usage: ./l99 build SERVICE VERSION

Build a Docker image and push up to Docker hub.

SERVICE   service name - adapter, meter, relay, etc.
VERSION   service version - e.g. 0.8.1-arm, latest, etc.

Might need to login to Docker Hub first, in order to push image there -

    docker login --username ladder99

Example
    ./l99 build adapter 0.8.0-arm
    ./l99 build relay latest
"

# show help if count of params is zero
if [ $# -eq 0 ]; then
    echo "$usage"
    exit 1
fi

SERVICE=$1
VERSION=$2
USERNAME=ladder99
TAG=$USERNAME/$SERVICE:$VERSION

pushd ./services/$SERVICE
docker build --tag $TAG .
popd 
docker image ls $USERNAME/$SERVICE

# push image to docker hub
docker push $TAG
