#!/bin/bash

usage="
Usage: ./l99 example

Run an example setup.
"

SETUP=./setups/example
PARAMS="agent adapter meter relay"
shell/linux/start $SETUP $PARAMS

echo
echo Running Ladder99 example pipeline.
echo Visit http://localhost in your browser.
