#!/bin/bash

usage="
Usage: ./l99 init SETUP

Initialize a new setup in ../setup-SETUP.

Example
    ./l99 init my-company
"

# show help if count of params is zero
if [ $# -eq 0 ]; then
    echo "$usage"
    exit 1
fi

# get dest folder
SETUP=$1
DEST=../setup-$SETUP
shift

# copy setup
# rsync has an --exclude param, but installing rsync on git bash for windows is complex - 
#  https://superuser.com/questions/701141/how-to-add-more-commands-to-git-bash
echo
echo Copying from setups/example...
cp -R setups/example $DEST \
&& rm -r $DEST/volumes/postgres \
&& rm -r $DEST/volumes/grafana/var \
&& rm -r $DEST/volumes/pgadmin \
&& echo Done. Try ./l99 start $SETUP
