#!/bin/bash

# list docker containers - fits narrow screen
# use `./l99 list -a` to show all services, including exited

# ---

# # show list
# docker container ls --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}\t{{.Image}}\t{{.Command}}'

# # sort alpha
# # see https://stackoverflow.com/questions/46173298/how-to-sort-or-order-results-docker-ps-format/49973096#49973096
# docker container ls --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}' | (read -r; printf "%s\n" "$REPLY"; sort -k 1 )

# get options, eg -a
OPTIONS=$*

COLUMNS='{{.Label "com.docker.compose.project"}}\t{{.Label "com.docker.compose.service"}}\t{{.Status}}\t{{.Ports}}'
docker container ls \
  $OPTIONS \
  --format "table $COLUMNS" \
 | (read -r; printf "%s\n" "$REPLY"; sort -k 1 )

# removed this
# --filter label=com.docker.compose.project \
