#!/bin/bash

# can't use profiles with this, because docker-compose doesn't handle them
# with stop, only services!

usage="
Usage: ./l99 stop SERVICES

Stop Ladder99 services.

To stop all running services, use ./l99 stop all
"

if [ $# -eq 0 ]; then
    echo "$usage"
    exit 1
fi

SERVICES=$*

if [ $SERVICES = "all" ]; then
  # CMD="docker stop $(docker ps -q)"
  # --force = no confirmation
  CMD="docker system prune --force"
else
  CMD="docker stop $SERVICES"
fi

# get command and call it
echo $CMD
bash -c "$CMD"
