#!/bin/bash

# can't use profiles with this, because docker-compose doesn't handle them
# with stop, only services!

# https://stackoverflow.com/questions/33362856/whats-the-difference-between-docker-stop-and-docker-rm

#. add prune option to clear up space?

usage="
Usage: ./l99 stop SERVICES

Stop Ladder99 services.

To stop all running services, use ./l99 stop all
"

if [ $# -eq 0 ]; then
    echo "$usage"
    exit 1
fi

SERVICES=$*

if [ $SERVICES = "all" ]; then
  # CMD="docker stop $(docker ps -q)"
  # --force = no confirmation
  # docker system prune --force \
  # && docker rm --force --volumes $(docker ps -q -a)
  # docker rm --force --volumes $(docker ps -q)
  # docker stop $(docker ps -q)
  # stop services from the ladder99 compose yaml
  IDS=$(docker ps -q --filter label=com.docker.compose.project=ladder99)
  if [ "$IDS" = "" ]; then
    echo All ladder99 services already stopped.
  else
    docker stop $IDS
  fi
else
  docker stop $SERVICES
fi
