#!/bin/bash

# can't use profiles with this, because docker-compose doesn't handle them
# with stop, only services!

usage="
Usage: ./l99 stop SERVICES

Stop Ladder99 services.
"

if [ $# -eq 0 ]; then
    echo "$usage"
    exit 1
fi

SERVICES=$*

# get command and call it
CMD="docker stop $SERVICES"
echo $CMD
bash -c "$CMD"
