#!/bin/bash
# run sql commands on edge db

SQL_FILE=$1

cat $SQL_FILE | docker run -i --rm postgres:13 sh -c \
    "export PGPASSWORD=$PGPASSWORD && psql -h $PGHOST -p $PGPORT -d $PGDATABASE -U $PGUSER"
