#!/bin/bash

export PLATFORM=${1:-'linux/amd64,linux/arm/v7,linux/arm64'}
echo $PLATFORM

# note: you have to use either --push or --load. 
# --load fails for multiarch, so we have to push to a registry, docker hub. 
# tag it with 'test' for now - then deploy script could retag them?

cd services/agent && \
docker buildx build \
  --platform=$PLATFORM \
  --tag=ladder99/mtconnect-agent:test \
  --push \
  .
