#!/bin/bash
# copy data to a named volume for the agent container to access.

SETUP=${1:-'pi'}

docker volume rm agent
docker volume create agent

../docker/cp setups/$SETUP/volumes/agent/agent.cfg agent /data/agent
../docker/cp setups/$SETUP/volumes/agent/devices.xml agent /data/agent
../docker/cp setups/$SETUP/volumes/agent/styles agent /data/agent
