{
 "title": "Microcontroller3",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "measurement": "cpu_temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "measurement": "cpu",
     "query": "SELECT \"usage_user\", \"usage_system\" FROM \"cpu\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  }
 ]
}