{
 "title": "Microcontroller",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Memory (bytes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT time, value as total\nFROM history_float\nWHERE\n  path='memory-total' and\n  $__timeFilter(\"time\")\nORDER BY time"
    },
    {
     "rawSql": "SELECT time, value as free\nFROM history_float\nWHERE\n  path='memory-free' and\n  $__timeFilter(\"time\")\nORDER BY time"
    },
    {
     "rawSql": "SELECT time, value as used\nFROM history_float\nWHERE\n  path='memory-used' and\n  $__timeFilter(\"time\")\nORDER BY time"
    }
   ]
  },
  {
   "title": "CPU (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT time, value as total\nFROM history_float\nWHERE\n  path='cpu-total' and\n  $__timeFilter(\"time\")\nORDER BY time"
    },
    {
     "rawSql": "SELECT time, value as system\nFROM history_float\nWHERE\n  path='cpu-system' and\n  $__timeFilter(\"time\")\nORDER BY time"
    },
    {
     "rawSql": "SELECT time, value as user\nFROM history_float\nWHERE\n  path='cpu-user' and\n  $__timeFilter(\"time\")\nORDER BY time"
    }
   ]
  },
  {
   "title": "Temperature (C)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT time, value as temp\nFROM history_float\nWHERE\n  path='temperature' and\n  $__timeFilter(\"time\")\nORDER BY time"
    }
   ]
  }
 ]
}