#!/bin/bash

usage="
Usage: l99 build SERVICE

Build a local Docker image as specified in services/docker-compose.yaml.
See also 'l99 buildx' for cross-platform images.

SERVICE     service name - adapter, meter, relay, etc.

Example
    l99 build adapter
    l99 build grafana
"

# show help if count of params is zero
if [ $# -eq 0 ]; then
    echo "$usage"
    exit
fi

SERVICE=$1

# use default builder, not multiplatform builder
# avoids problem with sending tarball to docker which can get stuck
# see https://github.com/docker/buildx/issues/107
# and build command in this folder
docker buildx use --default default

CMD="l99 compose build $SERVICE"

echo "Building a local image as specified by the services/docker-compose.yaml file..."
echo "$CMD"

bash -c "$CMD" \
&& echo \
&& l99 ls $SERVICE
