#!/bin/bash

# note: it's best to build each arch image separately, then combine them,
# because had problems with builds crashing.
#. better now?

#. get default service version from package.json - use jq to extract?
# but if package.json out of date

usage="
Usage: l99 build SERVICE VERSION [PLATFORMS]

Build a multiplatform Docker image and push up to Docker hub.

SERVICE     service name - adapter, meter, relay, etc.
VERSION     service version - e.g. 0.10.1, latest, etc.
PLATFORMS   platforms to build - leave off for default

Might need to login to Docker Hub first, in order to push image there -

    docker login --username ladder99

Example
    l99 build adapter 0.10.1
    l99 build relay latest
"

# show help if count of params is zero
if [ $# -eq 0 ]; then
    echo "$usage"
    exit
fi

SERVICE=$1
VERSION=$2
PLATFORMS=${3:-"linux/amd64,linux/arm64,linux/arm/v7"}

USERNAME=ladder99
TAG=$USERNAME/$SERVICE:$VERSION
SERVICE_DIR=services/$SERVICE

echo "Building an image as specified by the Dockerfile in '$SERVICE_DIR'..."
echo "Platform is" $PLATFORMS
docker buildx build --tag $TAG --platform $PLATFORMS $SERVICE_DIR \
&& echo \
&& echo "Listing $USERNAME/$SERVICE images..." \
&& docker image ls $USERNAME/$SERVICE \
&& echo "Pushing the image to Docker Hub..." \
&& docker push $TAG
