#!/bin/bash

usage="
Usage: l99 dev [SERVICES]

Start a docker service or services using their profile name(s).
Builds the image locally from the service Dockerfile.
See also l99 start.

SERVICES      space-delim list of services or profiles to start
  base        run all relevant services for a setup - eg adapter, agent, etc.
              (this is the default)

Example
    l99 dev meter
    l99 dev
"

# show help
# if [ $# -eq 0 ]; then
if [ "$1" = "-h" ]; then
    echo "$usage"
    exit
fi

# if no services specified, default to 'base'
SERVICES=${*:-base}

# make cmd and run it
CMD="l99 compose up --build $SERVICES"

echo "$CMD"
bash -c "$CMD"
