#!/bin/bash

# Print disk usage for current setup.

# get setup folder
SETUP=$(cat .l99_setup)
SETUP_DIR=setups/$SETUP

# note: sudo isn't always available, eg in git bash environment, so test
if hash sudo 2>/dev/null; then
    SUDO=sudo
else
    SUDO=
fi

echo
echo "Total disk usage"
df -h /
echo


echo "Docker images"
$SUDO du -hs /var/lib/docker
echo

echo "Docker volumes for different Ladder99 setups"
$SUDO du -d1 -h setups
echo

echo "Docker volumes for '$SETUP' setup"
$SUDO du -d1 -h $SETUP_DIR/volumes/
