#!/bin/bash

usage="
Usage: l99 download SETUP

Download a setup from the Ladder99 repository and make it the current setup.

Example:
    l99 download demo
    l99 download my-company
"

if [ $# -eq 0 ]; then
    echo "$usage"
    exit
fi

# get setup, eg 'test'
SETUP=$1
shift

# get setup folder, eg 'setups/test'
SETUP_FOLDER=setups/$SETUP

if [ -e $SETUP_FOLDER ]; then
    echo Setup folder \'$SETUP_FOLDER\' already exists. Please try again.
    exit 1
fi

git clone https://github.com/Ladder99/setup-$SETUP $SETUP_FOLDER \
&& echo $SETUP > .l99_setup \
&& shell/commands/using
