#!/bin/bash

repo_root="$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")"

usage="
Usage: l99 init SETUP

Initialize a new setup in setups/SETUP, and make it the current setup.

Example
    l99 init my-company
"

# show help if count of params is zero
if [ $# -eq 0 ]; then
    echo "$usage"
    exit
fi

# source folder
EXAMPLE="$repo_root/setups/example"

# get setup name
SETUP=$1
shift

# get setup folder
SETUP_FOLDER="$repo_root/setups/$SETUP"

# check if setup dir already exists
if [ -d "$SETUP_FOLDER" ]; then
  echo "Error: a folder for $SETUP already exists at $SETUP_FOLDER."
  echo "Please try a different setup name."
  exit 1
fi

# copy setup folder
echo
echo "Copying from '$EXAMPLE'..."

# need to specify everything explicitly here -
# alternative is installing rsync on gitbash, or ignoring cp errors,
# or using sudo to cp everything including potentially large pg folders.
# so, will need to keep this up-to-date if add more to the example folder!

# we copy agent folder for the agent.cfg and agent.xml files
# we copy grafana/etc for some dashboard pages

mkdir $SETUP_FOLDER \
&& mkdir $SETUP_FOLDER/services \
&& mkdir $SETUP_FOLDER/volumes \
&& mkdir $SETUP_FOLDER/volumes/grafana \
&& cp -R $EXAMPLE/volumes/agent $SETUP_FOLDER/volumes/agent/ \
&& cp -R $EXAMPLE/volumes/grafana/etc $SETUP_FOLDER/volumes/grafana/etc/ \
&& cp $EXAMPLE/.gitignore $SETUP_FOLDER \
&& cp $EXAMPLE/.env-example $SETUP_FOLDER \
&& cp $EXAMPLE/services/docker-compose.yaml $SETUP_FOLDER/services \
&& cp $EXAMPLE/README.md $SETUP_FOLDER \
&& cp $EXAMPLE/setup.yaml $SETUP_FOLDER \
&& "$repo_root/shell/commands/use" $SETUP \
&& echo "Done. Try 'l99 start'"

# old:
# need `2>/dev/null || :` to suppress the error msgs and errors in cp,
# see https://serverfault.com/a/153893/211025.
# but
# rsync has an --exclude param, but installing rsync on git bash for windows is complex -
#  https://superuser.com/questions/701141/how-to-add-more-commands-to-git-bash
# sudo cp -R setups/example $SETUP_FOLDER \
# cp -R setups/example $SETUP_FOLDER 2>/dev/null || : \
# && rm $ENVFILE \
# && rm -rf $SETUP_FOLDER/volumes/grafana/var \
# && rm -rf $SETUP_FOLDER/volumes/pgadmin \
# && rm -rf $SETUP_FOLDER/volumes/postgres \
# && rm -rf $SETUP_FOLDER/volumes/portainer \
