#!/bin/bash

repo_root="$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")"

usage="
Usage: l99 init SETUP

Initialize a new setup in setups/SETUP, and make it the current setup.

Example
    l99 init my-company
"

# show help if count of params is zero
if [ $# -eq 0 ]; then
    echo "$usage"
    exit
fi

# source folder
EXAMPLE="$repo_root/setups/example"

# get setup name
SETUP=$1
shift

# get setup folder
SETUP_FOLDER="$repo_root/setups/$SETUP"

# check if setup dir already exists
if [ -d "$SETUP_FOLDER" ]; then
  echo "Error: a folder for $SETUP already exists at $SETUP_FOLDER."
  echo "Please try a different setup name."
  exit 1
fi

# copy setup folder
echo
echo "Copying from '$EXAMPLE'..."

# need to specify everything explicitly here -
# alternative is installing rsync on gitbash, or ignoring cp errors,
# or using sudo to cp everything including potentially large pg folders.
# so, will need to keep this up-to-date if add more to the example folder!

# we copy agent folder for the agent.cfg and agent.xml files
# we copy grafana/etc for some dashboard pages

mkdir "$SETUP_FOLDER" "$SETUP_FOLDER"/{services,volumes,volumes/grafana} \
&& cp -r "$EXAMPLE/volumes/agent" "$SETUP_FOLDER/volumes/agent" \
&& cp -r "$EXAMPLE/volumes/grafana/etc" "$SETUP_FOLDER/volumes/grafana/etc" \
&& cp "$EXAMPLE/services/docker-compose.yaml" "$SETUP_FOLDER/services" \
&& cp "$EXAMPLE"/{.env-example,.gitignore,README.md,setup.yaml} "$SETUP_FOLDER" \
&& "$repo_root/shell/commands/use" "$SETUP" \
&& echo "Done. Try 'l99 start'"