#!/bin/bash

# list local ladder99 images

SERVICE=${*:-*} # eg *, grafana
USERNAME=ladder99

echo "Listing $USERNAME/$SERVICE images..."

docker image ls $USERNAME/$SERVICE \
 | (read -r; printf "%s\n" "$REPLY"; sort -k 1 )
