#!/bin/bash

# restart services

scripts_root="$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")/shell"

usage="
Usage: l99 restart [SERVICES]

Stop and start the specified Ladder99 services for the current setup.

See 'l99 start' for help.
"

# show help if count of params is zero
if [ $# -eq 0 ]; then
    echo "$usage"
    exit
fi

SERVICES=$*

echo "Stopping services..." \
&& "$scripts_root/l99" stop $SERVICES \
&& echo "Starting services..." \
&& "$scripts_root/l99" start $SERVICES
