#!/bin/bash

# run ladder99 pipeline using prebuilt images from docker hub.

usage="
Usage: l99 start [SERVICES]

Run the Ladder99 pipeline with a list of services/profiles to include.
Pulls images from Docker hub as needed.
See also l99 dev.

SERVICES      space-delim list of services or profiles to start
  base        run all relevant services for a setup - eg adapter, agent, etc.
              (this is the default)

Examples
    l99 start agent
    l99 start
"

# show help
# if [ $# -eq 0 ]; then
if [ "$1" = "-h" ]; then
    echo "$usage"
    exit
fi

# if no services specified, default to 'base'
SERVICES=${*:-base}

# make cmd and run it
# 'l99 compose up' runs with --no-build by default
CMD="l99 compose up $SERVICES"

echo "$CMD"
bash -c "$CMD"
