#!/bin/bash

# show status of docker containers - fits narrow screen
# use `l99 status -a` to show all services, including exited

# get options, eg -a
OPTIONS=$*

COLUMNS='{{.Label "com.docker.compose.project"}}\t{{.Label "com.docker.compose.service"}}\t{{.Status}}\t{{.Ports}}\t{{.Image}}'
docker container ls \
  $OPTIONS \
  --format "table $COLUMNS" \
  --filter label=com.docker.compose.project \
 | (read -r; printf "%s\n" "$REPLY"; sort -k 1 )
