#!/bin/bash

usage="
Usage: l99 use SETUP

Specify a setup to use for all following l99 commands.

Example:
    l99 use example
    l99 use my-company
"

if [ $# -eq 0 ]; then
    echo "$usage"
    exit
fi

SETUP=$1
shift

# get setup folder
SETUP_FOLDER=setups/$SETUP

# handle missing setup folder
if [ ! -e $SETUP_FOLDER ]; then
    echo "Setup folder '$SETUP_FOLDER' does not exist. Please try again."
    exit 1
fi

# save setup to a file
echo $SETUP > .l99_setup

shell/commands/using
