#!/bin/bash

repo_root="$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")"

# report the currently used setup

SETUP=$(cat "$repo_root/.l99_setup")
echo "Using '$SETUP' for Ladder99 setup, as found in the 'setups' folder."
