# application service
# polls agent and sends data to database

version: '3.7'

services:
  application:
    container_name: application
    image: node:15
    user: node
    working_dir: /home/node/app
    command: npm start
    environment:
      - AGENT_BASE_URL=http://agent:5000
      - INTERVAL=2000
      # # use current environment values for these
      # - PGHOST
      # - PGPORT
      # - PGDATABASE
      # - PGUSER
      # - PGPASSWORD
      - ARANGODB_URL=http://arangodb:8529
      - ARANGODB_DATABASE=ladder99-default
    # env_file:
    #   - ../../../.env
    networks:
      - ladder99
    volumes:
      - ../../../services/application:/home/node/app
    #   - ../volumes/application:/etc/application
    logging:
      options:
        max-size: '1m'

networks:
  ladder99:
    name: ladder99
