# mtconnect application
# polls agent and sends data to database

version: '3.7'

services:
  application:
    container_name: application
    image: node:15
    user: node
    working_dir: /home/node/app
    command: npm start
    environment:
      - AGENT_BASE_URL=http://agent:5000
      - FETCH_INTERVAL=2000
      - FETCH_COUNT=200
      - PGHOST
      - PGPORT
      - PGDATABASE
      - PGUSER
      - PGPASSWORD
    #. this fixes a problem on linux - will it still work on mac with this here?
    # see https://stackoverflow.com/a/67158212/243392
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - ladder99
    volumes:
      - ../../../services/application:/home/node/app
    #   - ../volumes/application:/etc/application
    logging:
      options:
        max-size: '1m'

networks:
  ladder99:
    name: ladder99
