version: '3.7'

services:
  agent:
    container_name: agent
    image: ladder99/mtconnect-agent:latest
    networks:
      - ladder99
    ports:
      - 5000:5000
    logging:
      options:
        max-size: '1m'

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    ports:
      - '9000:9000'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ../volumes/portainer:/data
    restart: always
    logging:
      driver: 'none'
    networks:
      - ladder99

networks:
  ladder99:
    name: ladder99
