# tapedeck docker-compose file

version: '3.8'

services:
  tapedeck:
    container_name: tapedeck
    build: .
    ports:
      - 1883:1883
    # init: true
    # these override any command line envars if set here
    # command: npm start -m $MODE -h $HOST -p $PORT -l $LOOP -f $FOLDER
    command: node src/tapedeck.js -m $MODE -h $HOST -p $PORT -l $LOOP -f $FOLDER
    environment:
      - MODE
      - FOLDER
      - HOST
      - PORT
      - LOOP
    volumes:
      - $FOLDER:/etc/tapedeck
    networks:
      - ladder99
    logging:
      options:
        max-size: '1m'

networks:
  ladder99:
    name: ladder99
