# tapedeck docker-compose file

version: '3.8'

services:
  tapedeck:
    container_name: tapedeck
    build: .
    ports:
      - 1883:1883
    # init: true
    environment:
      - HOST=host.docker.internal
      - PORT=1883
      - MODE=play
      - LOOP=true
    volumes:
      - $FOLDER:/etc/tapedeck
    networks:
      - ladder99
    logging:
      options:
        max-size: '1m'

networks:
  ladder99:
    name: ladder99
