#!/bin/bash

# watch and serve sphinx docs
# see docs/source/*.md

# note: sphinx docs are automatically built and available on git push at
# https://ladder99.readthedocs.io/en/latest/
# as long as the repo is public.
# if you need to build html locally, cd docs && make html

# note: -a rebuilds everything on a change - needed because the sidebar
# can get all out of whack otherwise.
sphinx-autobuild -a --port 8080 docs docs/build/html
