#!/bin/bash
# install node dependencies

cd services/adapter && npm install
cd services/application && npm install
cd services/compiler && npm install
cd services/simulator-mqtt && npm install
cd services/simulator-opc && npm install
cd services/diode/code/application/datadiode/contrib/nodejs && npm install

