adapter:
  model: ccs-pa
  properties:
    uuid: e05363af-95d1-4354-b749-8fbb09d3499f
    serialNumber: CCS124
    prefix: CCS124
  # sequences:
  #   startup: ccs-startup.js
  #   shutdown: ccs-shutdown.js
  # topics:
  #   read: l99/CCS124/evt/read
  #   status: l99/CCS124/evt/status
  # config:
  #   prefixDataItems: true
