{
 "title": "Paths",
 "tags": [ "client" ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "device", "label": "Device", "query": "select name from devices" }
  ]
 },
 "panels": [
  {
   "title": "Commanded Position (mm)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "yaxes": [
    { "format": "lengthmm" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  value as x\nFROM history_float\nWHERE \n  device='$device' and\n  path='axes/x/position-commanded' and\n  $__timeFilter(\"time\");"
    },
    {
     "rawSql": "SELECT\n  time,\n  value as y\nFROM history_float\nWHERE \n  device='$device' and\n  path='axes/y/position-commanded' and\n  $__timeFilter(\"time\");"
    },
    {
     "rawSql": "SELECT\n  time,\n  value as z\nFROM history_float\nWHERE \n  device='$device' and\n  path='axes/z/position-commanded' and\n  $__timeFilter(\"time\");\n"
    }
   ]
  },
  {
   "title": "Actual Position (mm)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "yaxes": [
    { "format": "lengthmm" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  value as x\nFROM history_float\nWHERE \n  device='$device' and\n  path='axes/x/position-actual' and\n  $__timeFilter(\"time\");"
    },
    {
     "rawSql": "SELECT\n  time,\n  value as y\nFROM history_float\nWHERE \n  device='$device' and\n  path='axes/y/position-actual' and\n  $__timeFilter(\"time\");"
    },
    {
     "rawSql": "SELECT\n  time,\n  value as z\nFROM history_float\nWHERE \n  device='$device' and\n  path='axes/z/position-actual' and\n  $__timeFilter(\"time\");\n"
    }
   ]
  },
  {
   "title": "Path 2d",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT time, value as x\nFROM history_float\nWHERE \n  device='$device'\n  and path='axes/x/position-actual'\n  and $__timeFilter(\"time\")\n  \n"
    },
    {
     "rawSql": "SELECT time, value as y\nFROM history_float\nWHERE \n  device='$device'\n  and path='axes/y/position-actual'\n  and $__timeFilter(\"time\")\n"
    }
   ]
  },
  {
   "title": "Path 3d",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT time,\n  SUM(CASE path WHEN 'axes/x/position-actual' THEN value ELSE 0 END) AS x,\n  SUM(CASE path WHEN 'axes/y/position-actual' THEN value ELSE 0 END) AS y,\n  SUM(CASE path WHEN 'axes/z/position-actual' THEN value ELSE 0 END) AS z\nFROM history_float\nWHERE \n  device='$device' and\n  $__timeFilter(\"time\")\nGROUP BY time\n;\n"
    }
   ]
  }
 ]
}