# docker-compose file

version: '3.8'

services:
  # record mqtt messages
  record:
    container_name: record
    build: .
    ports:
      - 1883:1883
    # init: true
    environment:
      - HOST=host.docker.internal
      - PORT=1883
      - MODE=record
      - FILE=/data/recording.csv
    #   - LOOP=true
    #   - LOOP_DELAY=3000
    volumes:
      - ./data:/data
    networks:
      - ladder99
    logging:
      options:
        max-size: '1m'

  # replay mqtt messages
  replay:
    container_name: replay
    build: .
    ports:
      - 1883:1883
    # init: true
    environment:
      - HOST=host.docker.internal
      - PORT=1883
      - MODE=replay
      - FILE=data/playback.csv
    #   - LOOP=true
    #   - LOOP_DELAY=3000
    networks:
      - ladder99
    logging:
      options:
        max-size: '1m'

  # sim-mqtt:
  #   container_name: sim-mqtt
  #   image: node:15.14-slim
  #   user: node
  #   working_dir: /home/node/app
  #   command: npm start
  #   environment:
  #     - MQTT_HOST=broker
  #     - MQTT_PORT=1883
  #     - DEVICE_ID=ccs-pa-001
  #     - MESSAGES_FILE=/etc/sim-mqtt/messages.js
  #     - MESSAGE_DELAY=1000
  #     - LOOP=true
  #     - LOOP_DELAY=3000
  #   volumes:
  #     - ../services/sim-mqtt:/home/node/app # has source code
  #     - ./$SETUP/volumes/sim-mqtt:/etc/sim-mqtt # has sim msgs
  #   networks:
  #     - ladder99
  #   logging:
  #     options:
  #       max-size: '1m'

networks:
  ladder99:
    name: ladder99
