#!/bin/bash

# compile a setup's config/setup.yaml to devices.xml

SETUP=$1  # setup subfolder, eg 'ccs-pa'

node pipeline/adapter/src/compiler/compile-xml.js \
  setups/$SETUP/setup.yaml \
  setups/$SETUP/volumes/agent/devices.xml

# # compile-xml and compile-compose
# compile SETUP='demo':
#     just compile-xml {{SETUP}}
#     just compile-compose {{SETUP}}

# # compile devices.xml from model setup.yaml
# compile-xml SETUP='demo':
#     node pipeline/adapter/src/compiler/compile-xml.js \
#     setups/{{SETUP}}/setup.yaml \
#     setups/{{SETUP}}/volumes/agent/devices.xml

# # compile docker-compose.yaml from setup.yaml
# compile-compose SETUP='demo':
#     echo todo
