#!/bin/bash
# copy data to a named volume for the adapter container to access.

# SETUP=${1:-'pi'}

# docker container create \
#   --name temp \
#   --volume adapter:/data/adapter \
#   busybox
# docker cp . temp:/data/adapter
# docker rm temp





# source .env
# $enterpwd ssh $PI "sudo mkdir -p /etc/ladder99/adapter"
# $enterpwd ssh $PI "sudo chown pi:pi /etc/ladder99/adapter"
# $enterpwd scp -p setups/{{SETUP}}/devices.yaml $PI:/etc/ladder99/adapter
# $enterpwd scp -pr models $PI:/etc/ladder99/adapter/models
