#!/bin/bash
# tapedeck - play/record mqtt messages
# specify play/record as parameter, eg
#     shell/tapedeck -m play -f ./recordings
#     shell/tapedeck -m record -f /Users/bburns/Desktop/tapedeck -h host.docker.internal

COMPOSE=services/tapedeck/compose.yaml

export MODE=$1
export FOLDER=$2
export HOST=$3
export PORT=$4
export LOOP=$5

docker-compose --file $COMPOSE up --build tapedeck
