#!/bin/bash
# run a setup

SETUP=${1:-'pi'}
SUFFIX=$2  # eg '-application'
SERVICE=$3

# compile devices.yaml to devices.xml
# sh/setups/compile $SETUP

# get the docker-compose config file
FILE=setups/$SETUP/docker/docker-compose$SUFFIX.yaml

# shut down
# don't do this as kills network when running two compose files
# docker-compose --file $FILE down

# get latest images
docker-compose --file $FILE pull

# run the setup
# don't remove orphans as kills other running services
# docker-compose --file $FILE up --build --remove-orphans $SERVICE
docker-compose --file $FILE up --build

# remove containers etc
# -f, --force   Don't ask to confirm removal
# -s, --stop    Stop the containers, if required, before removing
# -v            Remove any anonymous volumes attached to containers
docker-compose --file $FILE rm -fsv
