#!/bin/bash
# run sql command file on postgres db
# usage:
#   shell/db/migrate vmc 000-init.sql
#   etc

SETUP=$1
MIGRATION=$2

ENV_FILE=setups/$SETUP/.env
SQL_FILE=setups/$SETUP/migrations/$MIGRATION

export $(grep -v '^#'  $ENV_FILE | xargs) \
  && cat $SQL_FILE | docker run --env-file $ENV_FILE -i --rm postgres:13 sh -c \
    "psql -h $PGHOST -p $PGPORT -d postgres -U $PGUSER"
