#!/bin/bash
# run sql command file on postgres db
# usage:
#   shell/db/migrate vmc 000-init.sql
#   etc

SETUP=$1
MIGRATION=$2
SQL_FILE=setups/$SETUP/$MIGRATION
ENV_FILE=setups/$SETUP/.env

cat $SQL_FILE | eval $(cat $ENV_FILE) docker run -i --rm postgres:13 sh -c \
    "export PGPASSWORD=$PGPASSWORD && psql -h $PGHOST -p $PGPORT -d $PGDATABASE -U $PGUSER"
