#!/bin/sh

# build multiarch agent docker image and deploy to dockerhub
# example:
#   sh/agent/deploy :test linux/arm/7
#   sh/agent/deploy :1.7.0.3 linux/amd64,linux/arm64,linux/arm/v7

# note: we have to push the whole buildx image up to dockerhub as 
# it contains multiple architectures. you have to use either --push or 
# --load with buildx - if you just use --load, then when you try to deploy 
# the image to dockerhub later, it will only include one architecture.

# get platforms to merge
TAG=$1 # eg :latest
PLATFORM=$2 # eg linux/amd64,linux/arm64,linux/arm/v7
PATH=services/agent

# build image and push to docker hub
docker buildx build \
  --platform=$PLATFORM \
  --tag=ladder99/agent$TAG \
  --push \
  $PATH
