#!/bin/sh

# add a version tag to an existing image on docker hub.

# eg if build and push a multiagent image to docker hub,
# then need to add a version to it, can use this script.

VERSION=$1 # eg 1.7.0.3

docker buildx imagetools create --tag ladder99/agent:$VERSION ladder99/agent:latest
