#!/bin/bash

#. is this obsolete? we can use sh/start foo record, yes?

# recorder - a nodejs app to play/record device messages.
# first param is folder relative to current directory.
# specify play/record as parameter, eg
#     sh/recorder models/ccs-pa/recordings    # -m defaults to 'play'
#     sh/recorder recordings -m record -h host.docker.internal

if [ -z "$1" ]; then echo "Error: folder required as first argument"; exit 1; fi

# get first param then remove it from $* array
HOST_FOLDER=$1
shift

# build docker image for recorder
docker build --tag recorder services/recorder

# run the docker image as a container
# -it is for interactive terminal
# --init passes ctrl-c to node
# --rm removes the container when it's done
# --volume links a host folder to a folder inside the container.
# recorder will write to the container folder,
# and it'll be visible in the host folder.
# $* passes remaining params to the recorder node app.
CONTAINER_FOLDER=/etc/recorder
docker run --name recorder -it --init --rm -p 1883:1883 -p 8082:8082 \
  --volume "$(pwd)"/$HOST_FOLDER:$CONTAINER_FOLDER \
  recorder --folder $CONTAINER_FOLDER $*
