#!/bin/bash
# watch and serve sphinx docs

# -a rebuilds everything on a change - needed because the sidebar
# can get all out of whack otherwise.
sphinx-autobuild -a --port 8080 docs/source docs/build/html
