{
 "title": "Main",
 "tags": [ "client" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "Device",
    "query": "select uid from devices where uid <> 'Main/m'"
   },
   {
    "name": "sample_load",
    "label": "sample_load",
    "query": "linear[x],linear[y],linear[z],rotary[a],rotary[b],rotary[c]"
   },
   {
    "name": "query0",
    "query": "select path from dataitems where path like '$device/axes/%/load'"
   }
  ]
 },
 "panels": [
  { "title": "Axis Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$query0",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "repeat": "query0",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, value\nFROM history_float\nWHERE\n  -- path = concat('$device','/axes/', $sample_load, '/load')\n  path = $query0\n  and $__timeFilter(\"time\")\norder by time desc\nlimit 1"
    }
   ]
  },
  { "title": "Timeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Timeline",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT time, value as \"Availability\"\nFROM get_timeline('$device', '$device/availability', $__from, $__to, true, '1d')\n"
    },
    {
     "rawSql": "SELECT time, value as \"Controller Mode\"\nFROM get_timeline('$device', '$device/controller/path/controller_mode', $__from, $__to, true, '1d')\n"
    },
    {
     "rawSql": "SELECT time, value as \"Emergency Stop\"\nFROM get_timeline('$device', '$device/controller/emergency_stop', $__from, $__to, true, '1d')\n"
    },
    {
     "rawSql": "SELECT time, value as \"Execution\"\nFROM get_timeline('$device', '$device/controller/path/execution', $__from, $__to, true, '1d')\n"
    },
    {
     "rawSql": "SELECT time, value as \"Equipment Mode / Working\"\nFROM get_timeline('$device', '$device/equipment_mode-working', $__from, $__to, true, '1h')\n"
    },
    {
     "rawSql": "SELECT time, value as \"Equipment Mode / Delay\"\nFROM get_timeline('$device', '$device/equipment_mode-delay', $__from, $__to, true, '1h')\n"
    },
    {
     "rawSql": "SELECT time, value as \"Equipment Mode / Loaded\"\nFROM get_timeline('$device', '$device/equipment_mode-loaded', $__from, $__to, true, '1h')\n"
    }
   ]
  },
  { "title": "Temperature/Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT time, path, value\nFROM history_float\nWHERE\n  -- path='$device/axes/rotary[c]/temperature' and\n  path like '$device/axes/%/temperature' and\n  $__timeFilter(\"time\")\norder by time\n"
    },
    {
     "rawSql": "SELECT time, value as coolant\nFROM history_float\nWHERE\n  path='$device/systems/coolant/temperature' and\n  $__timeFilter(\"time\")\norder by time"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT time, path, value\nFROM history_float\nWHERE\n  -- device='$device' and\n  -- path='$device/axes/rotary[c]/load' and\n  path like '$device/axes/%/load' and\n  $__timeFilter(\"time\")\norder by time"
    }
   ]
  },
  { "title": "Speeds", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Path Feedrate (mm/sec)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  value as \"feedrate\"\nFROM history_float\nWHERE\n  -- device='$device' and\n  path='$device/controller/path/path_feedrate-actual' and\n  $__timeFilter(\"time\")"
    }
   ]
  },
  {
   "title": "Spindle Speed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT time, value as Actual\nFROM history_float\nWHERE\n  -- device='$device' and\n  -- path='axes/c/spindle_speed-actual' and\n  path='$device/axes/rotary[c]/rotary_velocity-actual' and\n  $__timeFilter(\"time\")"
    },
    {
     "rawSql": "SELECT time, value as Override\nFROM history_float\nWHERE\n  -- device='$device' and\n  -- path='axes/c/spindle-speed-override' and\n  path='$device/controller/path/rotary_velocity_override' and\n  $__timeFilter(\"time\")"
    }
   ]
  }
 ]
}