{
 "title": "Metrics",
 "tags": [ "client" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device",
    "query": "select path from devices order by path"
   }
  ]
 },
 "panels": [
  { "title": "$device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "device" },
  {
   "title": "cutting time",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "select time, value from history_float where path=concat($device,'/controller/accumulated_time-cut')"
    }
   ]
  },
  {
   "title": "$device",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "--select time, value from get_last_value($device, 'availability', '1w');\n\n-- this will be the new get_last_value fn\n-- select time, value as value from history_text\n-- where node_id=(select node_id from nodes where props->>'uid'=$device)\n--   and dataitem_id=(select node_id from nodes where props->>'shortPath'='availability')\n-- order by time desc\n-- limit 1;\n\nselect time, value as value from history_text\nwhere path = concat($device, '/availability')\norder by time desc\nlimit 1;\n\n"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\nwith\n  path_activity as (values (concat($device, '/controller/accumulated_time-cut'))),\n  available as (values (8.0)), -- hours that machine is available for use\n  now as (values (now())),\n  midnight as (values (date_trunc('day', (table now))))\nselect (table now) as time, (max(value)-min(value))/60.0/60.0/(table available) as availability\nfrom history_float\nwhere path = (table path_activity)\nand time >= (table midnight) and time < (table now)\n\n"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with \n  max_rate as (values (1200)), -- maximum production rate in parts per hour (pph)\n  now as (values (now())),\n  midnight as (values (date_trunc('day', (table now))))\nselect \n  (table now) as time, \n  (max(value)-min(value)) / \n  (max(extract(epoch from time))-min(extract(epoch from time))) / \n  (table max_rate) \n  as speed\nfrom history_float\nwhere path = concat($device, '/controller/path/part_count')\nand time >= (table midnight) and time < (table now)\n\n"
    }
   ]
  },
  {
   "title": "Quality",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with \n  now as (values (now())),\n  midnight as (values (date_trunc('day', (table now)))),\n  good_path as (values (concat($device, '/controller/path/part_count-good'))),\n  total_path as (values (concat($device, '/controller/path/part_count'))), -- or with '-all'?\n  good_parts as (\n    select value from history_float \n    where path=(table good_path) \n    and time>=(table midnight) and time<(table now)\n  ),\n  total_parts as (\n    select value from history_float \n    where path=(table total_path) \n    and time>=(table midnight) and time<(table now)\n  )\nselect \n  (table now) as time, \n  (table good_parts) / (table total_parts) as quality\n"
    }
   ]
  },
  {
   "title": "OEE",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- select now() as time, 0.5 as value\n\nselect now() as time, .5 as oee\n-- from history_float\n-- where path = concat($device, '/controller/path/part_count')\n-- and time > '2022-08-27'\n\n"
    }
   ]
  }
 ]
}