devices:

  device:
    id: dev
    name: CCS-PA
    uuid: 000
    sampleInterval: 10

    description:
      manufacturer: CCS
      model: Emergent-PA-Pneumatic
      serialNumber: 000
      text: Emergent Next Generation Print and Apply

    dataitems: []

    components:

      controller:
        id: controller
        nativeName: plc
        description: 
          text: Electronic board set responsible for coordinating all machine function.
        dataitems: []
        components:
          path:
            id: path1
            name: path
            dataitems: []

    systems:
      id: systems
      components:
        endeffector:
          id: end_effector
          dataitems: []
          compositions: []
        feeder:
          id: feeder
          dataitems: []
          compositions: []
