# database services

#. note: this currently expects data to be stored directly in ~/data folders
#. move to cloud?

version: '3.7'

services:
  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb:latest-pg13
    ports:
      - '5432:5432/tcp'
    networks:
      - ladder99
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: gralgrut
      POSTGRES_DB: ladder99
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - $HOME/data/postgres:/var/lib/postgresql/data

  grafana:
    container_name: grafana
    image: grafana/grafana:7.5.5
    ports:
      - '3003:3000/tcp'
    networks:
      - ladder99
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - $HOME/data/grafana:/var/lib/grafana
    user: pi

  pgadmin:
    container_name: pgadmin
    image: biarms/pgadmin4:latest
    ports:
      - '5050:5050/tcp'
    networks:
      - ladder99
    deploy:
      restart_policy:
        condition: on-failure

networks:
  ladder99:
    name: ladder99
