# docker-compose overrides

# minimally need version number
version: '3.8'

services:
  adapter:
    profiles:
      - all
  agent:
    profiles:
      - all
  postgres:
    profiles:
      - all
  relay:
    profiles:
      - all
