#!/bin/bash

# install dependencies needed for multiarch build

# run a container with the qemu emulator for multiarch builds
# see https://hub.docker.com/r/multiarch/qemu-user-static/
docker run --rm --privileged multiarch/qemu-user-static --reset --persistent yes

# create a multiarch builder
docker buildx create --name multiarch --driver docker-container --use
docker buildx inspect --bootstrap
