#!/bin/bash
# install node dependencies

npm --prefix services/adapter install
npm --prefix services/application install
npm --prefix services/compiler install
npm --prefix services/diode/code/application/datadiode/contrib/nodejs install
npm --prefix services/tapedeck install
