#!/bin/bash
# install doc building dependencies

# # create a virtual environment
# python3 -m venv ~/.venv/ladder99-venv

# # use virtual environment
# source ~/.venv/ladder99-venv/bin/activate

# for building docs
pip install -U Sphinx
pip install -r docs/requirements.txt
