# github workflow to build mtconnect and ladder99 agent docker images
#
# note: this workflow is used to build BOTH mtconnect AND ladder99 images
#
# instructions:
#
# to build the mtconnect agent (only need to do when version changes enough):
# 1. get current version from https://github.com/mtconnect/cppagent/blob/master/CMakeLists.txt
# 2. update the version value below - the second version number is the ladder99 xsl version.
# 3. use 'mtconnect-agent' for the service name below
# 4. COMMIT and PUSH the change to github
# 5. trigger the build-agent workflow manually from github actions page.
#     make sure you use the right branch - select in the 'Run workflow' dropdown.
#     will take a few hours for the multiarch build.
# 5. check docker hub to see that it's there
# 6. test the image with
#     docker run -it --rm -p 5000:5000 --pull always ladder99/mtconnect-agent:latest
#     and view in http://localhost:5000
#
# to build the ladder99 agent (the xsl ui on top of the mtconnect agent):
# 1. update the version value below - second number is ladder99 xsl version.
# 2. use 'agent' for service name below
# 3. COMMIT and PUSH the change to github
# 4. trigger the build-agent workflow manually from github actions page.
#     make sure you use the right branch - select in the 'Run workflow' dropdown.
#     this should just take a few minutes.
# 5. check docker hub to see that it's there
# 6. test the image with
#     docker run -it --rm -p 5000:5000 --pull always ladder99/agent:latest
#     and view in http://localhost:5000
#
# run manually at https://github.com/Ladder99/ladder99/actions
# secrets set at https://github.com/Ladder99/ladder99/settings/secrets/actions
# images hosted at https://hub.docker.com/r/ladder99/agent

name: build-agent

# define variables - used below
env:
  # note: service names correspond to folders in the pipeline folder
  # service: mtconnect-agent
  service: agent
  version: 1.7.0.3-0.1.2
  # for available platforms see output of a previous run -
  # ie the "Setup Docker BuildX" / "Inspect Builder" section
  # has eg "node_platforms": "linux/amd64,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6"
  # but the platforms must also be included in the os image chosen -
  # eg the ubuntu image doesn't include linux/arm/v6.
  platforms: linux/amd64,linux/arm64,linux/arm/v7

# let user run workflow manually from actions tab
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU emulator
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: pipeline/${{ env.service }}
          file: pipeline/${{ env.service }}/Dockerfile
          platforms: ${{ env.platforms }}

          # docker hub user/repo:tag
          tags: |
            ladder99/${{ env.service }}:latest
            ladder99/${{ env.service }}:${{ env.version }}

          # push to docker hub
          push: true
